In [2]:
import numpy as np
import pandas as pd
import pymysql
from sqlalchemy import create_engine

In [3]:
engine = create_engine('Enter your server address, USERNAME and Password, SocketName')

In [4]:
Customer_df = pd.read_sql_query('SELECT * FROM clients', engine)
Customer_df .head()

,id,fname,lname,email,address,city,state,zip,createdate,countries_id,...,last_ip_address_used,last_purchase_date,agents_id,cookie_auth,facebook_id,contact_email,guest,audience_reward,reset_hash,iata
0,78027,owen,McDonald,mco77@hotmail.com,4459 silver peak parkway,suwanee,ga,None,2011-07-06 15:02:55,NaN,...,None,None,NaN,None,None,None,0,None,None,None
1,78028,David,Headley,Forester7m@yahoo.com,123 St Johns PL,Brooklyn,NY,None,2011-08-11 19:28:38,NaN,...,None,None,NaN,None,None,None,0,None,None,None
2,78029,Vick,Nolfi,nolfilighthouse@aol.com,7586 Hudson Park Drive,Hudson,Ohio,None,2011-08-16 17:17:02,NaN,...,None,None,NaN,None,None,None,0,None,None,None
3,78030,Sheila,Salka,deela51@optonline.net,25-15 Southern Drive,Fair Lawn,New Jersey,None,2011-09-24 22:57:42,NaN,...,None,None,NaN,None,None,None,0,None,None,None
4,78031,Corey,McKenna,corey_mckenna@yahoo.com,526 F Street,Bakersfield,CA,None,2011-09-25 00:36:32,NaN,...,None,None,NaN,None,None,None,0,None,None,None

In [5]:
Customers = Customer_df.rename(columns={"id": "clients_id"})

In [6]:
Booking_df = pd.read_sql_query('SELECT * FROM bookings', engine)

In [7]:
Booking = pd.DataFrame(Booking_df.rename(columns={"id": "bookings_id"}))
Booking.head()

,bookings_id,clients_id,amount_local,currencies_id,amount_merchant,bookings_mediums_id,agents_id,clients_comments,amount_merchant_refunded,booking_time,notifications_count,is_archived,has_comments,imported_id,old_booking_id
0,101571,78027.0,NaN,1.0,NaN,4.0,NaN,None,None,2011-07-06 15:02:55,6.0,0,0,4332.0,NaN
1,101572,78028.0,NaN,1.0,NaN,4.0,NaN,None,None,2011-08-11 19:28:38,1.0,0,0,5890.0,NaN
2,101573,78029.0,NaN,1.0,NaN,4.0,NaN,None,None,2011-08-16 17:17:02,NaN,0,0,6123.0,NaN
3,101574,78030.0,NaN,1.0,NaN,4.0,NaN,None,None,2011-09-24 22:57:42,NaN,0,0,8076.0,NaN
4,101575,78031.0,NaN,1.0,NaN,4.0,NaN,None,None,2011-09-25 00:36:32,1.0,0,0,8085.0,NaN

In [8]:
bookings_details_df = pd.read_sql_query('SELECT * FROM bookings_details', engine)
bookings_details_df.head()

,id,bookings_id,events_id,promos_id,events_datetimes,amount_local,amount_converted,cancelled,cancelled_datetime,number_adults,...,distributor_tickets_list,pre_exclude_category,pre_exclude_reason,pre_exclude_users_id,pre_exclude_datetime,api_distributor_reference_id,users_id,old_bd_id,sales_channel,sales_channel_api
0,129936,103072.0,9.0,None,2013-05-07 09:30:00,0.0,NaN,0,NaT,4.0,...,None,NaN,,NaN,2017-05-23 16:47:00,None,NaN,NaN,None,0
1,130165,103242.0,91.0,None,2013-01-10 10:00:00,108.0,NaN,0,NaT,2.0,...,None,NaN,,NaN,2017-05-23 16:47:00,None,NaN,NaN,None,0
2,130547,103536.0,7.0,None,2013-05-06 08:35:00,0.0,NaN,0,NaT,2.0,...,None,NaN,,NaN,2017-05-23 16:47:00,None,NaN,NaN,None,0
3,131223,104066.0,7.0,None,2013-10-12 08:35:00,148.0,NaN,1,NaT,0.0,...,None,NaN,,NaN,2017-05-23 16:47:00,None,NaN,NaN,None,0
4,131334,104158.0,79.0,None,2013-05-02 10:30:00,40.0,NaN,0,NaT,2.0,...,None,NaN,,NaN,2017-05-23 16:47:00,None,NaN,NaN,None,0

In [9]:
Event_df = pd.read_sql_query('SELECT * FROM events', engine)
Event_df.head()

,id,name_short,name_long,name_listing,description_short,description_long,description_listing,sku,duration,is_active,...,country,country_code,latitude,longitude,language,allow_double_guides,disable_promos,map_link,hours_notify_within,is_on_sale
0,1,Pompeii - Best of Pompeii,The Best of Pompeii Tour: Unveiling The Buried...,Best of Pompeii Tour,Few places send shivers up your spine like Pom...,<h3>STEP BACK IN TIME AT POMPEII ARCHAEOLOGICA...,"Get the best from your time in Pompeii, coveri...",55.0,180.0,1.0,...,Italy,IT,40.742101,14.480625,english,0,0,https://www.google.com/maps/d/viewer?authuser=...,26,0
1,2,Rome - Welcome to Rome,Welcome to Rome: Twilight City Stroll & Gelato...,Welcome to Rome,The aim of this tour is simple Ã¢Â€Â“ to offer yo...,"<img src=""https://app.resrc.it/O=20(40)/s=W150...",See the top sights of RomeÃ¢Â€Â™s historic center...,40.0,150.0,1.0,...,Italy,IT,41.905698,12.482327,english,0,0,https://www.google.com/maps/d/viewer?mid=1_rPH...,26,0
2,3,Rome - Crypts & Catacombs,"Crypts, Bones & Catacombs: An Underground Tour...","Crypts, Bones & Catacombs",Just the word Ã¢Â€Â˜catacombÃ¢Â€Â™ is enough to shiv...,"<h3>VISIT THE BEST, LEAST-VISITED ROME CATACOM...","Visit Rome's most impressive Catacomb, explore...",34.0,180.0,1.0,...,Italy,IT,41.904809,12.488374,english,0,0,https://www.google.com/maps/d/viewer?mid=1k8pa...,26,0
3,5,"Z-Colosseum - VIP Access (ONLY Nov23, Dec18 @ ...","VIP Access - Colosseum Underground, Arena & To...",,"Recently and for the first time in history, th...",Why take this tour?\r\n\r\nUnlike other touris...,,NaN,210.0,0.0,...,Italy,IT,NaN,NaN,english,0,0,,26,0
4,6,Rome - Food Tour,"Rome Food Tour with Pizza-Making, Trattoria Ta...",Rome Food Tour,"On this immersive tour, weÃ¢Â€Â™ll teach you what...",<h3>EXPLORE THE TRATTORIAS OF THE JEWISH GHETT...,Join our expert foodies on an exploration of R...,114.0,210.0,1.0,...,Italy,IT,41.895502,12.472004,english,0,0,https://www.google.com/maps/d/viewer?mid=1_Gxa...,26,0

In [13]:
Event_df = pd.DataFrame(Event_df.rename(columns={"id": "events_id"}))

In [10]:
users_df =  pd.read_sql_query('SELECT * FROM users', engine)
users_df.head()

,id,fname,lname,status,created,last_modified,username,password,role,email,reset_hash,reset_datetime,cookie_auth
0,5,Philip,Hawkins,1.0,2017-03-23 13:15:04,2015-02-19 18:41:19,philip,c5659318160217c0ac935ef64c03bb4e,admin,philip@walks.org,None,2015-02-19 20:55:17,92803b3ef896762b49c92b313dde70ad:8fd00dcd7b951...
1,6,Habtom,W,NaN,2018-01-11 16:16:00,2015-02-19 18:41:19,habtom,0a7cbd25cb6eac751b588dd3b21059e9,archived,habtomwalks@gmail.comARCHIVED,None,2015-02-19 18:41:19,92b5615707f19942a85ba25823b593ec:84398bf2f3a0b...
2,8,notRealAug5,notRealAug5,NaN,2013-08-06 16:07:07,2013-08-06 16:07:07,walks,test,admin,notRealAug5@walks.org,None,2015-02-19 18:41:19,None
3,9,Emma,del Balzo di Presenzano,NaN,2015-02-19 18:41:19,2015-02-19 18:41:19,emma,4cf6888ba3f1578a678fb24d7248a498,admin,emma@walks.org,,2013-09-12 23:24:40,8a556971d34a5f37d382dd4632e78153:a5c4dc6a95e8b...
4,10,Brandon,Oddo,NaN,2013-08-28 15:20:09,2013-08-28 15:20:09,Brandon,7ede9788c3c58bf9cb78147c155f0eff,admin,brandon@walks.org,None,2015-02-19 18:41:19,42540b9f42d292e727bbbb1486779112:56149000f7c3a...

In [48]:
users_df["Full_Name"] = users_df["fname"] + "_" + users_df["lname"]

In [11]:
Booking_clients_df = pd.merge(Booking, Customers , on='clients_id')

In [12]:
Booking_clients_details = pd.merge(Booking_clients_df, bookings_details_df , on='bookings_id')

In [15]:
Booking_clients_details_event = pd.merge(Booking_clients_details, Event_df, on='events_id')

In [25]:
Booking_clients_details_event.head()

,bookings_id,clients_id,amount_local_x,currencies_id_x,amount_merchant,bookings_mediums_id,agents_id_x,clients_comments,amount_merchant_refunded,booking_time,notifications_count,is_archived_x,has_comments,imported_id,old_booking_id,fname,lname,email,address,city_x,state,zip,createdate,countries_id,mobile_number,home_number,title,password,account_status,learned_about_walks,is_subscribed,last_time_logged_in,last_ip_address_used,last_purchase_date,agents_id_y,cookie_auth,facebook_id,contact_email,guest,audience_reward,reset_hash,iata,id,events_id,promos_id,events_datetimes,amount_local_y,amount_converted,cancelled,cancelled_datetime,number_adults,number_students,number_children,number_seniors,number_infants,res_expiry_date,is_paid,pre_exclude,distributors_id,distributor_reference,events_timeslots,transaction_id,bookings_type,bookings_note,stagegroup,stage_id,booking_date,is_archived_y,is_orphaned,is_listed_payment,adults_price_charged,students_price_charged,children_price_charged,seniors_price_charged,infants_price_charged,payment_transaction_number,is_refund,is_invoiced,private_group,package_id,package_stage,imported_promo,noshow,addon_exists,date_modified,exchange_rate,email_sent,charged_local_amount,charged_usd_amount,amount_local_fullprice,charged_converted_amount,api_cancellation_reference,hold_reservation_expiry,utc_hold_expiration,api_booking_status,distributor_tickets_list,pre_exclude_category,pre_exclude_reason,pre_exclude_users_id,pre_exclude_datetime,api_distributor_reference_id,users_id,old_bd_id,sales_channel,sales_channel_api,name_short,name_long,name_listing,description_short,description_long,description_listing,sku,duration,is_active,is_package,pack_1_events_id,pack_2_events_id,pack_1_time,pack_2_time,pack_1_price_percent,pack_2_price_percent,expires,staging,pax_max,hard_max,horizon,currencies_id_y,color,adults_price,students_price,children_price,seniors_price,infants_price,lateDiscount,latePercentage,guide_procedures,group_size,critical_hours,stall_hours,visible,needs_transport,needs_tickets,needs_guides,needs_escort,remove_guide_conflict,needs_equipment,guide_bring_cash,private_base_price,private_adults_price,private_seniors_price,private_students_price,private_children_price,private_infants_price,bullet1,bullet2,bullet3,sites_included,description_extended,url_name,price_includes,important_information,cs_description,ticketTimeAfterStart,needs_headsets,headsets_min,internal_note_g,internal_note_p,trans_pickup_g,trans_pickup_p,trans_dropoff_g,trans_dropoff_p,itinerary_g,itinerary_p,transport_start_after,transport_duration,custom_event,group_private,pace,meet_before,mp_text_g,mp_text_p,endpoint_g,endpoint_p,directions_g,directions_p,mp_image,mp_link,popularity,stall_hours_private,needs_coords,coords_min,page_title,meta_description,display_duration,display_days,display_time,wistia,video,charity_id,street_number,street,city_y,main_city,city_code,zip_code,province_code,country,country_code,latitude,longitude,language,allow_double_guides,disable_promos,map_link,hours_notify_within,is_on_sale,Total_Pax,Full_Name
0,101571,78027,NaN,1.0,NaN,4.0,NaN,None,None,2011-07-06 15:02:55,6.0,0,0,4332.0,NaN,owen,McDonald,mco77@hotmail.com,4459 silver peak parkway,suwanee,ga,None,2011-07-06 15:02:55,NaN,None,4046931364,None,82c09bdecd24d283b737bbf82084519d,active,Returning Customer,0,None,None,None,NaN,None,None,None,0,None,None,None,138565,83,None,2013-06-24 12:10:00,686.0,NaN,1,NaT,14.0,0.0,0.0,0.0,0.0,2015-02-19 18:41:06,0,0,NaN,,100,None,Group,undefined,NaN,2.000083e+18,2013-05-17 12:25:35,1,0,1,49.00,44.00,39.00,44.00,0.00,None,NaN,0.0,Group,NaN,NaN,None,0,1.0,2015-02-19 18:41:06,NaN,0.0,NaN,NaN,NaN,NaN,None,0000-00-00 00:00:00,0000-00-00 00:00:00,None,None,NaN,,NaN,2017-05-23 16:47:00,None,NaN,NaN,None,0,Tuscany - Tuscan Farmhouse,Cooking Classes in Tuscany with Farmhouse Expe...,Tuscan Farmhouse Cooking Class,Escape the city for the day and spend a day le...,"<img src=""https://app.resrc.it/O=20(40)/s=W150...",Learn to cook Tuscan food the Italian way and ...,164.0,360.0,0.0,0,69.0,69.0,19:52:00,19:52:00,NaN,NaN,2017-07-26 14:36:39,0.0,12.0,1,365.0,NaN,#7e5b1c,139,134,129,139,0.00,0,0,===SPECIAL INSTRUCTIONS===\r\n\r\nGroup tour: ...,12.0,129.0,12.0,0.0,0,0,1,0,0,0,,440.0,98.0,98.0,94.0,70.0,0.0,<p>Discover the very best of ItalyÃ¢Â€Â™s country...,"<p>With this exclusive offer, guests spend a d...",<p>This small group cooking classes from Tusca...,An authentic Tuscan farm & vineyard,,cooking-classes-in-tuscany,Return train transport from Rome to the farmho...,Please notify us if you have food allergies or...,"<a href=""http://e.walks.org/index.php?title=Ev...",0,0,NaN,"Alina is treated as a guide, but paid as a site.","Alina is treated as a guide, but paid as a site.",,,,,Group tour: Clients meet coordinator at 8.30am...,Group tour: Clients meet coordinator at 8.30am...,0.0,NaN,0,Group,0.0,15,"This tour meets at Termini Train Station, at t...","This tour meets at Termini Train Station, at t...",At Termini train station,At Termini Train station,A walks representative will meet you inside th...,A walks representative will meet you inside th...,,www.walksofitaly.com/farmhousechiusimeeting,24.0,57,1,1,Cooking Classes in Tuscany at an Authentic Far...,Spend the day cooking Tuscan specialties with ...,10hrs 15mins,,8:30AM,None,,2.0,None,None,None,Rome,ROM,None,None,Italy,IT,NaN,NaN,english,0,0,,26,0,14.0,owen McDonald
1,101571,78027,NaN,1.0,NaN,4.0,NaN,None,None,2011-07-06 15:02:55,6.0,0,0,4332.0,NaN,owen,McDonald,mco77@hotmail.com,4459 silver peak parkway,suwanee,ga,None,2011-07-06 15:02:55,NaN,None,4046931364,None,82c09bdecd24d283b737bbf82084519d,active,Returning Customer,0,None,None,None,NaN,None,None,None,0,None,None,None,138566,83,None,2013-05-24 11:00:00,288.0,NaN,1,NaT,3.0,0.0,0.0,1.0,0.0,2015-02-19 18:41:07,0,0,NaN,,100,None,Private,undefined,NaN,2.000083e+18,2013-05-17 12:27:16,1,0,1,49.00,44.00,39.00,44.00,0.00,None,NaN,0.0,Private,NaN,NaN,None,0,NaN,2015-02-19 18:41:07,NaN,0.0,NaN,NaN,NaN,NaN,None,0000-00-00 00:00:00,0000-00-00 00:00:00,None,None,NaN,,NaN,2017-05-23 16:47:00,None,NaN,NaN,None,0,Tuscany - Tuscan Farmhouse,Cooking Classes in Tuscany with Farmhouse Expe...,Tuscan Farmhouse Cooking Class,Escape the city for the day and spend a day le...,"<img src=""https://app.resrc.it/O=20(40)/s=W150...",Learn to cook Tuscan food the Italian way and ...,164.0,360.0,0.0,0,69.0,69.0,19:52:00,19:52:00,NaN,NaN,2017-07-26 14:36:39,0.0,12.0,1,365.0,NaN,#7e5b1c,139,134,129,139,0.00,0,0,===SPECIAL INSTRUCTIONS===\r\n\r\nGroup tour: ...,12.0,129.0,12.0,0.0,0,0,1,0,0,0,,440.0,98.0,98.0,94.0,70.0,0.0,<p>Discover the very best of ItalyÃ¢Â€Â™s country...,"<p>With this exclusive offer, guests spend a d...",<p>This small group cooking classes from Tusca...,An authentic Tuscan farm & vineyard,,cooking-classes-in-tuscany,Return train transport from Rome to the farmho...,Please notify us if you have food allergies or...,"<a href=""http://e.walks.org/index.php?title=Ev...",0,0,NaN,"Alina is treated as a guide, but paid as a site.","Alina is treated as a guide, but paid as a site.",,,,,Group tour: Clients meet coordinator at 8.30am...,Group tour: Clients meet coordinator at 8.30am...,0.0,NaN,0,Group,0.0,15,"This tour meets at Termini Train Station, at t...","This tour meets at Termini Train Station, at t...",At Termini train station,At Termini Train station,A walks representative will meet you inside th...,A walks representative will meet you inside th...,,www.walksofitaly.com/farmhousechiusimeeting,24.0,57,1,1,Cooking Classes in Tuscany at an Authentic Far...,Spend the day cooking Tuscan specialties with ...,10hrs 15mins,,8:30AM,None,,2.0,None,None,None,Rome,ROM,None,None,Italy,IT,NaN,NaN,english,0,0,,26,0,4.0,owen McDonald
2,106525,82127,NaN,1.0,NaN,4.0,NaN,None,None,2013-02-22 16:25:02,1.0,0,1,28245.0,NaN,Pat,Ogle-Collins,pat@wizardofodysseys.com,PO Box 7,Aldie,VA,None,2013-02-22 16:25:02,NaN,None,7033274912,None,527e1171f3d3d26ea97967cfa44c20f3,active,,0,None,None,None,408.0,None,None,None,0,None,None,None,134485,83,None,2013-09-26 10:00:00,330.0,NaN,0,NaT,2.0,0.0,0.0,0.0,0.0,2015-02-19 18:41:07,1,0,NaN,,100,None,Private,None,1.0,2.000083e+18,2013-02-22 08:28:52,1,0,1,99,94,79,94,0.00,None,NaN,0.0,Private,NaN,NaN,None,0,0.0,2015-02-19 18:41:07,NaN,1.0,NaN,NaN,NaN,NaN,None,0000-00-00 00:00:00,0000-00-00 00:00:00,None,None,NaN,,NaN,2017-05-23 16:47:00,None,NaN,NaN,None,0,Tuscany - Tuscan Farmhouse,Cooking Classes in Tuscany with Farmhouse Expe...,Tuscan Farmhouse Cooking Class,Escape the city for the day and spend a day le...,"<img src=""https://app.resrc.it/O=20(40)/s=W150...",Learn to cook Tuscan food the Italian way and ...,164.0,360.0,0.0,0,69.0,69.0,19:52:00,19:52:00,NaN,NaN,2017-07-26 14:36:39,0.0,12.0,1,365.0,NaN,#7e5b1c,139,134,129,139,0.00,0,0,===SPECIAL INSTRUCTIONS===\r\n\r\nGroup tour: ...,12.0,129.0,12.0,0.0,0,0,1,0,0,0,,440.0,98.0,98.0,94.0,70.0,0.0,<p>Discover the very best of ItalyÃ¢Â€Â™s country...,"<p>With this exclusive offer, guests spend a d...",<p>This small group cooking classes from Tusca...,An authentic Tuscan farm & vineyard,,cooking-classes-in-tuscany,Return train transport from Rome to the farmho...,Please notify us if you have food allergies or...,"<a href=""http://e.walks.org/index.php?title=Ev...",0,0,NaN,"Alina is treated as a guide, but paid as a site.","Alina is treated as a guide, but paid as a site.",,,,,Group tour: Clients meet coordinator at 8.30am...,Group tour: Clients meet coordinator at 8.30am...,0.0,NaN,0,Group,0.0,15,"This tour meets at Termini Train Station, at t...","This tour meets at Termini Train Station, at t...",At Termini train station,At Termini Train station,A walks representative will meet you inside th...,A walks representative will meet you inside th...,,www.walksofitaly.com/farmhousechiusimeeting,24.0,57,1,1,Cooking Classes in Tuscany at an Authentic Far...,Spend the day cooking Tuscan specialties with ...,10hrs 15mins,,8:30AM,None,,2.0,None,None,None,Rome,ROM,None,None,Italy,IT,NaN,NaN,english,0,0,,26,0,2.0,Pat Ogle-Collins
3,106981,82524,NaN,1.0,NaN,4.0,NaN,None,None,2013-03-14 16:41:42,NaN,0,0,29490.0,NaN,Emily,Pelligreen,epelligreen@cox.net,x,x,x,None,2013-03-14 16:41:42,NaN,None,6027036004,None,cbd235c1cedabfeb1cdb92bdcc7cb19c,active,,0,None,None,None,NaN,None,None,None,0,None,None,None,135114,83,None,2013-04-16 12:10:00,547.0,NaN,0,NaT,4.0,0.0,0.0,0.0,0.0,2015-02-19 18:41:07,1,0,NaN,,None,None,4,None,NaN,2.000083e+18,2013-03-14 09:41:42,1,0,1,369.00,0,79.00,84.00,0.00,None,NaN,NaN,Private,NaN,NaN,None,0,NaN,2015-02-19 18:41:07,NaN,1.0,NaN,NaN,NaN,NaN,None,0000-00-00 00:00:00,0000-00-00 00:00:00,None,None,NaN,,NaN,2017-05-23 16:47:00,None,NaN,NaN,None,0,Tuscany - Tuscan Farmhouse,Cooking Classes in Tuscany with Farmhouse Expe...,Tuscan Farmhouse Cooking Class,Escape the city for the day and spend a day le...,"<img src=""https://app.resrc.it/O=20(40)/s=W150...",Learn to cook Tuscan food the Italian way and ...,164.0,360.0,0.0,0,69.0,69.0,19:52:00,19:52:00,NaN,NaN,2017-07-26 14:36:39,0.0,12.0,1,365.0,NaN,#7e5b1c,139,134,129,139,0.00,0,0,===SPECIAL INSTRUCTIONS===\r\n\r\nGroup tour: ...,12.0,129.0,12.0,0.0,0,0,1,0,0,0,,440.0,98.0,98.0,94.0,70.0,0.0,<p>Discover the very best of ItalyÃ¢Â€Â™s country...,"<p>With this exclusive offer, guests spend a d...",<p>This small group cooking classes from Tusca...,An authentic Tuscan farm & vineyard,,cooking-classes-in-tuscany,Return train transport from Rome to the farmho...,Please notify us if you have food allergies or...,"<a href=""http://e.walks.org/index.php?title=Ev...",0,0,NaN,"Alina is treated as a guide, but paid as a site.","Alina is treated as a guide, but paid as a site.",,,,,Group tour: Clients meet coordinator at 8.30am...,Group tour: Clients meet coordinator at 8.30am...,0.0,NaN,0,Group,0.0,15,"This tour meets at Termini Train Station, at t...","This tour meets at Termini Train Station, at t...",At Termini train station,At Termini Train station,A walks representative will meet you inside th...,A walks representative will meet you inside th...,,www.walksofitaly.com/farmhousechiusimeeting,24.0,57,1,1,Cooking Classes in Tuscany at an Authentic Far...,Spend the day cooking Tuscan specialties with ...,10hrs 15mins,,8:30AM,None,,2.0,None,None,None,Rome,ROM,None,None,Italy,IT,NaN,NaN,english,0,0,,26,0,4.0,Emily Pelligreen
4,106982,82525,NaN,1.0,NaN,4.0,NaN,None,None,2013-03-14 17:33:35,NaN,0,0,29492.0,NaN,Lisa,Nelson,lnelson@davenportauto.com,132 Steeplechase Road,Rocky Mount,NC,None,2013-03-14 17:33:35,NaN,None,252-443-3855,None,4492b8903eb0f28643df8e618c7ba4c7,active,Search Engine Browsing,0,None,None,None,NaN,None,None,None,0,None,None,None,135117,83,None,2013-05-03 12:10:00,396.0,NaN,0,NaT,4.0,0.0,0.0,0.0,0.0,2015-02-19 18:41:03,1,0,NaN,,None,None,4,None,NaN,1.000083e+18,2013-03-14 13:48:02,1,0,1,99.00,0,79.00,84.00,0.00,None,NaN,NaN,Group,NaN,NaN,None,0,NaN,2015-02-19 18:41:03,NaN,1.0,NaN,NaN,NaN,NaN,None,0000-00-00 00:00:00,0000-00-00 00:00:00,None,None,NaN,,NaN,2017-05-23 16:47:00,None,NaN,NaN,None,0,Tuscany - Tuscan Farmhouse,Cooking Classes in Tuscany with Farmhouse Expe...,Tuscan Farmhouse Cooking Class,Escape the city for the day and spend a day le...,"<img src=""https://app.resrc.it/O=20(40)/s=W150...",Learn to cook Tuscan food the Italian way and ...,164.0,360.0,0.0,0,69.0,69.0,19:52:00,19:52:00,NaN,NaN,2017-07-26 14:36:39,0.0,12.0,1,365.0,NaN,#7e5b1c,139,134,129,139,0.00,0,0,===SPECIAL INSTRUCTIONS===\r\n\r\nGroup tour: ...,12.0,129.0,12.0,0.0,0,0,1,0,0,0,,440.0,98.0,98.0,94.0,70.0,0.0,<p>Discover the very best of ItalyÃ¢Â€Â™s country...,"<p>With this exclusive offer, guests spend a d...",<p>This small group cooking classes from Tusca...,An authentic Tuscan farm & vineyard,,cooking-classes-in-tuscany,Return train transport from Rome to the farmho...,Please notify us if you have food allergies or...,"<a href=""http://e.walks.org/index.php?title=Ev...",0,0,NaN,"Alina is treated as a guide, but paid as a site.","Alina is treated as a guide, but paid as a site.",,,,,Group tour: Clients meet coordinator at 8.30am...,Group tour: Clients meet coordinator at 8.30am...,0.0,NaN,0,Group,0.0,15,"This tour meets at Termini Train Station, at t...","This tour meets at Termini Train Station, at t...",At Termini train station,At Termini Train station,A walks representative will meet you inside th...,A walks representative will meet you inside th...,,www.walksofitaly.com/farmhousechiusimeeting,24.0,57,1,1,Cooking Classes in Tuscany at an Authentic Far...,Spend the day cooking Tuscan specialties with ...,10hrs 15mins,,8:30AM,None,,2.0,None,None,None,Rome,ROM,None,None,Italy,IT,NaN,NaN,english,0,0,,26,0,4.0,Lisa Nelson

In [17]:
pd.options.display.max_columns = 250

In [20]:
pd.options.display.max_rows = 250

In [21]:
Booking_clients_details_event.count()

bookings_id                     227209
clients_id                      227209
amount_local_x                  193320
currencies_id_x                 227205
amount_merchant                 193321
bookings_mediums_id              70242
agents_id_x                        434
clients_comments                 17315
amount_merchant_refunded             0
booking_time                    227209
notifications_count              33333
is_archived_x                   227209
has_comments                    227209
imported_id                      33886
old_booking_id                   17315
fname                           227209
lname                           227200
email                           227156
address                         227208
city_x                          227197
state                           227092
zip                             193215
createdate                      227209
countries_id                     68918
mobile_number                   192786
home_number                      82300
title                            48750
password                         53282
account_status                   75458
learned_about_walks             104483
is_subscribed                   227209
last_time_logged_in              17250
last_ip_address_used             16919
last_purchase_date               39593
agents_id_y                      59062
cookie_auth                      16922
facebook_id                      16919
contact_email                    39593
guest                           227209
audience_reward                  16919
reset_hash                         724
iata                               218
id                              227209
events_id                       227209
promos_id                            0
events_datetimes                227209
amount_local_y                  227180
amount_converted                129659
cancelled                       227209
cancelled_datetime                  92
number_adults                   227208
number_students                 227209
number_children                 227209
number_seniors                  227209
number_infants                  227209
res_expiry_date                 227209
is_paid                         227209
pre_exclude                     227209
distributors_id                  58121
distributor_reference           227209
events_timeslots                 23784
transaction_id                  154135
bookings_type                    53080
bookings_note                    20531
stagegroup                      193287
stage_id                        227209
booking_date                    227209
is_archived_y                   227209
is_orphaned                     227209
is_listed_payment               227209
adults_price_charged            201437
students_price_charged          199384
children_price_charged          182519
seniors_price_charged           186182
infants_price_charged           180335
payment_transaction_number      141472
is_refund                            2
is_invoiced                       6481
private_group                   227209
package_id                        9242
package_stage                     4635
imported_promo                   76365
noshow                          227209
addon_exists                       123
date_modified                   227209
exchange_rate                   154636
email_sent                      224030
charged_local_amount            154637
charged_usd_amount              154637
amount_local_fullprice           28906
charged_converted_amount        129659
api_cancellation_reference       19065
hold_reservation_expiry         227209
utc_hold_expiration             227209
api_booking_status               34825
distributor_tickets_list         17306
pre_exclude_category                26
pre_exclude_reason              227209
pre_exclude_users_id                21
pre_exclude_datetime            227209
api_distributor_reference_id     27075
users_id                          2208
old_bd_id                        17306
sales_channel                     1104
sales_channel_api               227209
name_short                      227209
name_long                       227209
name_listing                    227209
description_short               227209
description_long                227209
description_listing             227209
sku                             220661
duration                        227034
is_active                       227209
is_package                      227209
pack_1_events_id                212107
pack_2_events_id                212107
pack_1_time                     212107
pack_2_time                     212107
pack_1_price_percent             13256
pack_2_price_percent             13256
expires                         227209
staging                         156650
pax_max                         226986
hard_max                        227209
horizon                         227167
currencies_id_y                     24
color                           227209
adults_price                    227209
students_price                  227209
children_price                  227209
seniors_price                   227209
infants_price                   227209
lateDiscount                    227209
latePercentage                  227209
guide_procedures                227209
group_size                      227189
critical_hours                  226960
stall_hours                     226960
visible                         227209
needs_transport                 227209
needs_tickets                   227209
needs_guides                    227209
needs_escort                    227209
remove_guide_conflict           227209
needs_equipment                 227209
guide_bring_cash                168440
private_base_price              171029
private_adults_price            170916
private_seniors_price           169239
private_students_price          170812
private_children_price          170812
private_infants_price           130573
bullet1                         227209
bullet2                         227209
bullet3                         227209
sites_included                  227209
description_extended            227209
url_name                        227209
price_includes                  227209
important_information           227209
cs_description                  227209
ticketTimeAfterStart            227209
needs_headsets                  227209
headsets_min                    203383
internal_note_g                 227209
internal_note_p                 227209
trans_pickup_g                  227209
trans_pickup_p                  227209
trans_dropoff_g                 227209
trans_dropoff_p                 227209
itinerary_g                     227209
itinerary_p                     227209
transport_start_after           227209
transport_duration               53551
custom_event                    227209
group_private                   227209
pace                            227209
meet_before                     227209
mp_text_g                       227209
mp_text_p                       227209
endpoint_g                      227209
endpoint_p                      227209
directions_g                    227209
directions_p                    227209
mp_image                        198735
mp_link                         198735
popularity                      227209
stall_hours_private             227209
needs_coords                    227209
coords_min                      227209
page_title                      227202
meta_description                227202
display_duration                227202
display_days                    227202
display_time                    227202
wistia                               0
video                           227202
charity_id                       64350
street_number                   121459
street                          192603
city_y                          176055
main_city                       227209
city_code                       227209
zip_code                        193724
province_code                   221988
country                         226359
country_code                    227209
latitude                        193619
longitude                       193619
language                        227209
allow_double_guides             227209
disable_promos                  227209
map_link                        227209
hours_notify_within             227209
is_on_sale                      227209
dtype: int64

In [31]:
Booking_clients_details_event.cancelled.value_counts()

0    214171
1     13038
Name: cancelled, dtype: int64

In [32]:
Booking_clients_details_event.is_paid.value_counts()

1    214050
0     13159
Name: is_paid, dtype: int64

In [22]:
Booking_clients_details_event["Total_Pax"] = Booking_clients_details_event["number_adults"] + Booking_clients_details_event["number_students"] + Booking_clients_details_event["number_children"] + Booking_clients_details_event["number_seniors"] + Booking_clients_details_event["number_infants"]

In [24]:
Booking_clients_details_event["Full_Name"] = Booking_clients_details_event["fname"] + " " + Booking_clients_details_event["lname"]

In [29]:
Booking_clients_details_event_paid = pd.DataFrame(Booking_clients_details_event[Booking_clients_details_event.cancelled == 0])

In [33]:
Booking_clients_details_event_selected = pd.DataFrame(Booking_clients_details_event_paid[["bookings_id", "clients_id", "amount_local_x", "booking_time","Full_Name", "fname", "lname", "email", 
                                    "id", "events_id","events_datetimes", "amount_local_y", "amount_converted", "cancelled", 
                                    "cancelled_datetime", "Total_Pax", "is_paid", "bookings_note", "booking_date", "users_id", "name_short",
                                   "pax_max", "hard_max", "group_size"]])

In [34]:
Booking_clients_details_event_selected.head()

,bookings_id,clients_id,amount_local_x,booking_time,Full_Name,fname,lname,email,id,events_id,events_datetimes,amount_local_y,amount_converted,cancelled,cancelled_datetime,Total_Pax,is_paid,bookings_note,booking_date,users_id,name_short,pax_max,hard_max,group_size
2,106525,82127,NaN,2013-02-22 16:25:02,Pat Ogle-Collins,Pat,Ogle-Collins,pat@wizardofodysseys.com,134485,83,2013-09-26 10:00:00,330.0,NaN,0,NaT,2.0,1,None,2013-02-22 08:28:52,NaN,Tuscany - Tuscan Farmhouse,12.0,1,12.0
3,106981,82524,NaN,2013-03-14 16:41:42,Emily Pelligreen,Emily,Pelligreen,epelligreen@cox.net,135114,83,2013-04-16 12:10:00,547.0,NaN,0,NaT,4.0,1,None,2013-03-14 09:41:42,NaN,Tuscany - Tuscan Farmhouse,12.0,1,12.0
4,106982,82525,NaN,2013-03-14 17:33:35,Lisa Nelson,Lisa,Nelson,lnelson@davenportauto.com,135117,83,2013-05-03 12:10:00,396.0,NaN,0,NaT,4.0,1,None,2013-03-14 13:48:02,NaN,Tuscany - Tuscan Farmhouse,12.0,1,12.0
5,107742,82585,NaN,2013-04-07 16:40:40,Gregory Meehan,Gregory,Meehan,sgrmeehan@msn.com,136193,83,2013-05-16 12:10:00,725.0,NaN,0,NaT,6.0,1,None,2013-04-07 09:40:40,NaN,Tuscany - Tuscan Farmhouse,12.0,1,12.0
7,159870,83943,0.0,2016-01-07 16:57:33,Thomas Fusco,Thomas,Fusco,maryanne.desmond@protravelinc.com,198957,83,2016-05-12 08:30:00,278.0,NaN,0,NaT,2.0,1,None,2016-01-07 16:57:33,NaN,Tuscany - Tuscan Farmhouse,12.0,1,12.0

In [35]:
Booking_clients_details_event_selected.is_paid.value_counts()

1    213833
0       338
Name: is_paid, dtype: int64

In [36]:
Booking_clients_details_event_selected_paid = pd.DataFrame(Booking_clients_details_event_selected[Booking_clients_details_event_selected.is_paid == 1])

In [37]:
Booking_clients_details_event_selected_paid.Full_Name.count()

213826

In [38]:
Booking_clients_details_event_selected_paid.Full_Name.nunique()

141961

# Time Filter Cleaninng

In [40]:
Booking_Clean_1st = Booking_clients_details_event_selected_paid[Booking_clients_details_event_selected_paid.booking_date.notnull()]

In [41]:
Booking_Clean_2nd = pd.DataFrame(Booking_Clean_1st[Booking_Clean_1st.booking_date != "0000-00-00 00:00:00"])

In [42]:
Booking_clients_3rd = Booking_Clean_2nd[Booking_Clean_2nd.events_datetimes.notnull()]

In [45]:
Booking_Sclean = pd.DataFrame(Booking_clients_3rd[Booking_clients_3rd.events_datetimes != "0000-00-00 00:00:00"]).copy()

In [46]:
Booking_Sclean["events_datetimes"] = pd.to_datetime(Booking_Sclean["events_datetimes"])

In [47]:
Booking_Sclean["booking_date"] = pd.to_datetime(Booking_Sclean["booking_date"])

# Selecting From 2017 event time period

In [49]:
Booking_Event_2017 = pd.DataFrame(Booking_Sclean[Booking_Sclean.events_datetimes > "2016-12-31"])

In [51]:
Booking_Event_2017.Full_Name.count()

99669

# Neglecting company users from the dataset by (email = walks.org) and names

# <font color = "Blue">Clean Data Frame Creation</font>

In [50]:
Booking_Event_2017_ScleanNeg = pd.DataFrame(Booking_Event_2017[~Booking_Event_2017.Full_Name.isin(users_df["Full_Name"])])

In [52]:
Booking_Event_2017_ScleanNeg.Full_Name.count()

99669

# Creating Counts for number time name appears then creating cound for number time booking_id appears

In [53]:
Booking_Event_2017_ScleanNeg["Counts_Name"] = Booking_Event_2017_ScleanNeg.groupby(['Full_Name'])['amount_local_y'].transform('count')

In [54]:
Booking_Event_2017_ScleanNeg["Counts_Booking"] = Booking_Event_2017_ScleanNeg.groupby(['bookings_id'])['Full_Name'].transform('count')

In [57]:
Booking_Event_2017_ScleanNeg["unique_Person_event"] = Booking_Event_2017_ScleanNeg["bookings_id"].map(str) + Booking_Event_2017_ScleanNeg["email"]

In [ ]:
Booking_Event_2017_ScleanNeg["unique_Person_count_event"] = Booking_Event_2017_ScleanNeg.groupby(['unique_Person_event'])['email'].transform('count')

In [84]:
z = {1: 'Jan', 2: 'Feb', 3: 'March', 4: 'April', 5: 'May', 6: 'June', 7: 'July', 8: 'August', 9:'Sept', 10:'Oct', 11:'Nov', 12: 'Dec'}

# What I used for conversion for month and date, Here is example

df['year'] = pd.DatetimeIndex(df['ArrivalDate']).year
df['month'] = pd.DatetimeIndex(df['ArrivalDate']).month

or

df['year'] = df['ArrivalDate'].dt.year
df['month'] = df['ArrivalDate'].dt.month

or

df['month_year'] = df.date_column.dt.to_period('M')
df['month_year'] = df.date_column.dt.to_period('2M')


For Date conversion, 
booking_event["Booking_Datetime"] = booking_event["Booking Datetime"].dt.date

For WeekDay conversion,
booking_event['day_of_week'] = booking_event['Booking_Datetime'].dt.weekday_name

Datetime conversion,
booking_event["Booking Datetime"] = pd.to_datetime(booking_event["Booking Datetime"])

In [77]:
Booking_Event_2017_ScleanNeg["Event_month"] = Booking_Event_2017_ScleanNeg["events_datetimes"].dt.month

In [92]:
Booking_Event_2017_ScleanNeg["Booking_month"] = Booking_Event_2017_ScleanNeg["booking_date"].dt.month

In [90]:
Booking_Event_2017_ScleanNeg["Event_month"].replace(z, inplace=True)

In [94]:
Booking_Event_2017_ScleanNeg["Booking_month"].replace(z, inplace=True)

# Convert into just Date

In [102]:
Booking_Event_2017_ScleanNeg["Booking_DateOnly"] = Booking_Event_2017_ScleanNeg["booking_date"].dt.date

In [103]:
Booking_Event_2017_ScleanNeg["Event_DateOnly"] = Booking_Event_2017_ScleanNeg["events_datetimes"].dt.date

# For Two month selection

In [96]:
Booking_Event_2017_ScleanNeg["2Month_Period_event"] = Booking_Event_2017_ScleanNeg["events_datetimes"].dt.to_period('2M')

In [98]:
Booking_Event_2017_ScleanNeg["2Month_Period_booking"] = Booking_Event_2017_ScleanNeg["booking_date"].dt.to_period('2M')

In [104]:
Booking_Event_2017_ScleanNeg.head()

,bookings_id,clients_id,amount_local_x,booking_time,Full_Name,fname,lname,email,id,events_id,events_datetimes,amount_local_y,amount_converted,cancelled,cancelled_datetime,Total_Pax,is_paid,bookings_note,booking_date,users_id,name_short,pax_max,hard_max,group_size,Counts_Name,Counts_Booking,unique_Person_event,unique_Person_count_event,Event_month,Booking_month,2Month_Period_event,2Month_Period_booking,Booking_DateOnly,Event_DateOnly
240,18912337,78277,276.0,2017-03-21 18:37:29,Jerrit Ripley,Jerrit,Ripley,Jerrit.Ripley@imastalkyou.com,262150,6,2017-05-26 10:00:00,276.0,411.03,0,NaT,5.0,1,None,2017-03-21 18:37:33,NaN,Rome - Food Tour,36.0,0,12.0,2.0,1,18912337Jerrit.Ripley@imastalkyou.com,1,May,March,2017-05,2017-03,2017-03-21,2017-05-26
247,18910156,78995,345.0,2017-03-13 00:18:26,Kevin Wolfe,Kevin,Wolfe,Michaelcullum62@live.com,259844,6,2017-07-11 10:00:00,345.0,380.88,0,NaT,5.0,1,None,2017-03-13 00:18:27,NaN,Rome - Food Tour,36.0,0,12.0,3.0,2,18910156Michaelcullum62@live.com,2,July,March,2017-07,2017-03,2017-03-13,2017-07-11
286,19121833,82196,0.0,2017-07-10 19:39:28,George Pinches,George,Pinches,kchammett@yahoo.com,300823,6,2017-10-05 10:00:00,766.0,NaN,0,NaT,11.0,1,None,2017-07-11 17:38:12,NaN,Rome - Food Tour,36.0,0,12.0,2.0,2,19121833kchammett@yahoo.com,2,Oct,July,2017-10,2017-07,2017-07-11,2017-10-05
393,18914550,84786,138.0,2017-03-30 13:42:01,Bunny Rosen,Bunny,Rosen,Kathleen@easeintoitaly.com,264390,6,2017-05-29 10:00:00,138.0,152.79,0,NaT,2.0,1,None,2017-03-30 13:42:02,NaN,Rome - Food Tour,36.0,0,12.0,1.0,1,18914550Kathleen@easeintoitaly.com,1,May,March,2017-05,2017-03,2017-03-30,2017-05-29
409,19113382,85203,0.0,2017-06-19 13:28:11,Emma del Balzo,Emma,del Balzo,emma@walks.org,292084,6,2017-06-23 10:00:00,267.0,NaN,0,NaT,3.0,1,None,2017-06-19 13:34:52,NaN,Rome - Food Tour,36.0,0,12.0,12.0,9,19113382emma@walks.org,9,June,June,2017-06,2017-06,2017-06-19,2017-06-23

In [107]:
Booking_Event_2017_ScleanNeg.tail()

,bookings_id,clients_id,amount_local_x,booking_time,Full_Name,fname,lname,email,id,events_id,events_datetimes,amount_local_y,amount_converted,cancelled,cancelled_datetime,Total_Pax,is_paid,bookings_note,booking_date,users_id,name_short,pax_max,hard_max,group_size,Counts_Name,Counts_Booking,unique_Person_event,unique_Person_count_event,Event_month,Booking_month,2Month_Period_event,2Month_Period_booking,Booking_DateOnly,Event_DateOnly
227197,40024990,421502,0.00,2017-12-19 15:52:51,Greg Airbnb,Greg,Airbnb,gregairbnb@gregairbnb.com,427038,1157,2017-12-23 11:30:00,0.00,NaN,0,NaT,2.0,1,None,2017-12-19 15:53:12,418.0,Air BNB Twisted Statue Tour,10.0,0,10.0,1.0,1,40024990gregairbnb@gregairbnb.com,1,Dec,Dec,2017-12,2017-12,2017-12-19,2017-12-23
227201,40019819,418108,76.67,2017-11-18 06:08:20,Daniel Brake,Daniel,Brake,shortynz@gmail.com,421647,1136,2017-12-11 09:00:00,76.67,92.00,0,NaT,1.0,1,None,2017-11-18 06:08:21,NaN,Statue of Liberty and OWO,40.0,0,20.0,1.0,1,40019819shortynz@gmail.com,1,Dec,Nov,2017-12,2017-11,2017-11-18,2017-12-11
227203,40025013,421516,194.56,2017-12-19 18:19:53,Norman Kaiser,Norman,Kaiser,normkaiser1@comcast.net,427056,1136,2018-05-18 09:00:00,194.56,230.00,0,NaT,2.0,1,None,2017-12-19 18:19:54,NaN,Statue of Liberty and OWO,40.0,0,20.0,2.0,1,40025013normkaiser1@comcast.net,1,May,Dec,2018-05,2017-12,2017-12-19,2018-05-18
227207,40029530,424857,1107.00,2018-01-16 19:47:17,Willy Singh,Willy,Singh,willy.singh35@gmail.com,431534,241,2018-04-05 07:00:00,805.00,1015.66,0,NaT,5.0,1,None,2018-01-16 19:47:19,NaN,Rome - Florence from Rome,15.0,0,15.0,2.0,2,40029530willy.singh35@gmail.com,2,April,Jan,2018-04,2018-01,2018-01-16,2018-04-05
227208,40029583,424903,901.40,2018-01-16 23:51:54,Kathleen Canavan,Kathleen,Canavan,jkccanavan@yahoo.com,431587,241,2018-03-31 07:00:00,490.00,617.70,0,NaT,3.0,1,None,2018-01-16 23:51:57,NaN,Rome - Florence from Rome,15.0,0,15.0,3.0,3,40029583jkccanavan@yahoo.com,3,March,Jan,2018-03,2018-01,2018-01-16,2018-03-31

# Experimenting Area

In [105]:
Booking_Event_2017_ScleanNeg[Booking_Event_2017_ScleanNeg.Full_Name == "Kevin Wolfe"]

,bookings_id,clients_id,amount_local_x,booking_time,Full_Name,fname,lname,email,id,events_id,events_datetimes,amount_local_y,amount_converted,cancelled,cancelled_datetime,Total_Pax,is_paid,bookings_note,booking_date,users_id,name_short,pax_max,hard_max,group_size,Counts_Name,Counts_Booking,unique_Person_event,unique_Person_count_event,Event_month,Booking_month,2Month_Period_event,2Month_Period_booking,Booking_DateOnly,Event_DateOnly
247,18910156,78995,345.0,2017-03-13 00:18:26,Kevin Wolfe,Kevin,Wolfe,Michaelcullum62@live.com,259844,6,2017-07-11 10:00:00,345.0,380.88,0,NaT,5.0,1,None,2017-03-13 00:18:27,NaN,Rome - Food Tour,36.0,0,12.0,3.0,2,18910156Michaelcullum62@live.com,2,July,March,2017-07,2017-03,2017-03-13,2017-07-11
8395,18910156,78995,345.0,2017-03-13 00:18:26,Kevin Wolfe,Kevin,Wolfe,Michaelcullum62@live.com,296610,3,2017-07-12 14:00:00,0.0,NaN,0,NaT,5.0,1,None,2017-06-30 21:02:25,NaN,Rome - Crypts & Catacombs,45.0,1,15.0,3.0,2,18910156Michaelcullum62@live.com,2,July,June,2017-07,2017-06,2017-06-30,2017-07-12
74949,18910171,78995,285.0,2017-03-13 01:23:48,Kevin Wolfe,Kevin,Wolfe,Michaelcullum62@live.com,259862,89,2017-07-10 19:30:00,285.0,314.44,0,NaT,3.0,1,None,2017-03-13 01:23:49,NaN,Rome - Colosseum at Night,24.0,1,24.0,3.0,1,18910171Michaelcullum62@live.com,1,July,March,2017-07,2017-03,2017-03-13,2017-07-10

In [106]:
Booking_Event_2017_ScleanNeg[Booking_Event_2017_ScleanNeg.Full_Name == "Bunny Rosen"]

,bookings_id,clients_id,amount_local_x,booking_time,Full_Name,fname,lname,email,id,events_id,events_datetimes,amount_local_y,amount_converted,cancelled,cancelled_datetime,Total_Pax,is_paid,bookings_note,booking_date,users_id,name_short,pax_max,hard_max,group_size,Counts_Name,Counts_Booking,unique_Person_event,unique_Person_count_event,Event_month,Booking_month,2Month_Period_event,2Month_Period_booking,Booking_DateOnly,Event_DateOnly
393,18914550,84786,138.0,2017-03-30 13:42:01,Bunny Rosen,Bunny,Rosen,Kathleen@easeintoitaly.com,264390,6,2017-05-29 10:00:00,138.0,152.79,0,NaT,2.0,1,None,2017-03-30 13:42:02,NaN,Rome - Food Tour,36.0,0,12.0,1.0,1,18914550Kathleen@easeintoitaly.com,1,May,March,2017-05,2017-03,2017-03-30,2017-05-29

In [108]:
Booking_Event_2017_ScleanNeg[Booking_Event_2017_ScleanNeg.Full_Name == "Kathleen Canavan"]

,bookings_id,clients_id,amount_local_x,booking_time,Full_Name,fname,lname,email,id,events_id,events_datetimes,amount_local_y,amount_converted,cancelled,cancelled_datetime,Total_Pax,is_paid,bookings_note,booking_date,users_id,name_short,pax_max,hard_max,group_size,Counts_Name,Counts_Booking,unique_Person_event,unique_Person_count_event,Event_month,Booking_month,2Month_Period_event,2Month_Period_booking,Booking_DateOnly,Event_DateOnly
48013,40029583,424903,901.4,2018-01-16 23:51:54,Kathleen Canavan,Kathleen,Canavan,jkccanavan@yahoo.com,431585,7,2018-03-29 07:30:00,262.0,330.28,0,NaT,3.0,1,None,2018-01-16 23:51:56,NaN,Vatican - Pristine Sistine,108.0,0,12.0,3.0,3,40029583jkccanavan@yahoo.com,3,March,Jan,2018-03,2018-01,2018-01-16,2018-03-29
182594,40029583,424903,901.4,2018-01-16 23:51:54,Kathleen Canavan,Kathleen,Canavan,jkccanavan@yahoo.com,431586,9,2018-03-28 13:30:00,166.0,209.26,0,NaT,3.0,1,None,2018-01-16 23:51:57,NaN,Rome - Premium Colosseum,45.0,0,15.0,3.0,3,40029583jkccanavan@yahoo.com,3,March,Jan,2018-03,2018-01,2018-01-16,2018-03-28
227208,40029583,424903,901.4,2018-01-16 23:51:54,Kathleen Canavan,Kathleen,Canavan,jkccanavan@yahoo.com,431587,241,2018-03-31 07:00:00,490.0,617.70,0,NaT,3.0,1,None,2018-01-16 23:51:57,NaN,Rome - Florence from Rome,15.0,0,15.0,3.0,3,40029583jkccanavan@yahoo.com,3,March,Jan,2018-03,2018-01,2018-01-16,2018-03-31

In [71]:
Booking_Event_2017_ScleanNeg.unique_Person_count_event.value_counts()

1      77449
2      13948
3       4065
4       1924
5        975
6        522
7        287
135      135
8        112
9         90
10        70
11        55
12        24
13        13
Name: unique_Person_count_event, dtype: int64

In [72]:
Booking_Event_2017_ScleanNeg.Counts_Name.value_counts()

1.0      55049
2.0      23351
3.0       9705
4.0       5024
5.0       2717
6.0       1458
7.0        897
8.0        480
9.0        271
11.0       156
135.0      135
10.0       130
12.0       120
13.0        65
14.0        42
16.0        32
21.0        21
15.0        15
0.0          1
Name: Counts_Name, dtype: int64

In [73]:
Booking_Event_2017_ScleanNeg.Counts_Booking.value_counts()

1      77449
2      13948
3       4065
4       1924
5        975
6        522
7        287
135      135
8        112
9         90
10        70
11        55
12        24
13        13
Name: Counts_Booking, dtype: int64

In [64]:
Booking_Event_2017_ScleanNeg[Booking_Event_2017_ScleanNeg.unique_Person_event == "18910156Michaelcullum62@live.com"]

,bookings_id,clients_id,amount_local_x,booking_time,Full_Name,fname,lname,email,id,events_id,events_datetimes,amount_local_y,amount_converted,cancelled,cancelled_datetime,Total_Pax,is_paid,bookings_note,booking_date,users_id,name_short,pax_max,hard_max,group_size,Counts_Name,Counts_Booking,unique_Person_event,unique_Person_count_event
247,18910156,78995,345.0,2017-03-13 00:18:26,Kevin Wolfe,Kevin,Wolfe,Michaelcullum62@live.com,259844,6,2017-07-11 10:00:00,345.0,380.88,0,NaT,5.0,1,None,2017-03-13 00:18:27,NaN,Rome - Food Tour,36.0,0,12.0,3.0,2,18910156Michaelcullum62@live.com,2
8395,18910156,78995,345.0,2017-03-13 00:18:26,Kevin Wolfe,Kevin,Wolfe,Michaelcullum62@live.com,296610,3,2017-07-12 14:00:00,0.0,NaN,0,NaT,5.0,1,None,2017-06-30 21:02:25,NaN,Rome - Crypts & Catacombs,45.0,1,15.0,3.0,2,18910156Michaelcullum62@live.com,2

In [66]:
George_Pinches = Booking_Event_2017_ScleanNeg[Booking_Event_2017_ScleanNeg.Full_Name == "George Pinches"]

In [70]:
George_Pinches.drop_duplicates(subset=['events_id'], keep=False)

,bookings_id,clients_id,amount_local_x,booking_time,Full_Name,fname,lname,email,id,events_id,events_datetimes,amount_local_y,amount_converted,cancelled,cancelled_datetime,Total_Pax,is_paid,bookings_note,booking_date,users_id,name_short,pax_max,hard_max,group_size,Counts_Name,Counts_Booking,unique_Person_event,unique_Person_count_event
286,19121833,82196,0.0,2017-07-10 19:39:28,George Pinches,George,Pinches,kchammett@yahoo.com,300823,6,2017-10-05 10:00:00,766.0,NaN,0,NaT,11.0,1,None,2017-07-11 17:38:12,NaN,Rome - Food Tour,36.0,0,12.0,2.0,2,19121833kchammett@yahoo.com,2
16316,19121833,82196,0.0,2017-07-10 19:39:28,George Pinches,George,Pinches,kchammett@yahoo.com,300824,2,2017-10-03 14:00:00,509.0,NaN,0,NaT,9.0,1,None,2017-07-11 17:38:55,NaN,Rome - Welcome to Rome,115.0,0,20.0,2.0,2,19121833kchammett@yahoo.com,2

In [ ]:
Most event = Booking_Event_2017_ScleanNeg[Booking_Event_2017_ScleanNeg.Full_Name == "George Pinches"]

### 1st Scenrio : 
  For Particular Person:
  IF they have same booking ID and different event ID (Unique IDS)

In [109]:
Greater_than_5 = pd.DataFrame(Booking_Event_2017_ScleanNeg[Booking_Event_2017_ScleanNeg.Counts_Name > 5])

In [110]:
Greater_than_5.head()

,bookings_id,clients_id,amount_local_x,booking_time,Full_Name,fname,lname,email,id,events_id,events_datetimes,amount_local_y,amount_converted,cancelled,cancelled_datetime,Total_Pax,is_paid,bookings_note,booking_date,users_id,name_short,pax_max,hard_max,group_size,Counts_Name,Counts_Booking,unique_Person_event,unique_Person_count_event,Event_month,Booking_month,2Month_Period_event,2Month_Period_booking,Booking_DateOnly,Event_DateOnly
409,19113382,85203,0.0,2017-06-19 13:28:11,Emma del Balzo,Emma,del Balzo,emma@walks.org,292084,6,2017-06-23 10:00:00,267.0,NaN,0,NaT,3.0,1,None,2017-06-19 13:34:52,NaN,Rome - Food Tour,36.0,0,12.0,12.0,9,19113382emma@walks.org,9,June,June,2017-06,2017-06,2017-06-19,2017-06-23
868,124070,95784,0.0,2014-06-19 08:00:00,Manuela Valenti GUIDE TRAINING,Manuela,Valenti GUIDE TRAINING,manuelavalenti4@gmail.com,331273,6,2017-11-23 09:45:00,69.0,NaN,0,NaT,1.0,1,None,2017-10-24 08:00:33,54.0,Rome - Food Tour,36.0,0,12.0,6.0,6,124070manuelavalenti4@gmail.com,6,Nov,Oct,2017-11,2017-10,2017-10-24,2017-11-23
869,124070,95784,0.0,2014-06-19 08:00:00,Manuela Valenti GUIDE TRAINING,Manuela,Valenti GUIDE TRAINING,manuelavalenti4@gmail.com,424594,6,2017-12-16 09:45:00,0.0,NaN,0,NaT,1.0,1,None,2017-12-01 10:26:58,54.0,Rome - Food Tour,36.0,0,12.0,6.0,6,124070manuelavalenti4@gmail.com,6,Dec,Dec,2017-12,2017-12,2017-12-01,2017-12-16
1191,18914984,105464,138.0,2017-04-01 09:07:41,Jay Berringer,Jay,Berringer,jay.berringer@hundredacre.de,264811,6,2017-04-10 10:00:00,138.0,138.0,0,NaT,2.0,1,None,2017-04-01 09:07:43,NaN,Rome - Food Tour,36.0,0,12.0,6.0,1,18914984jay.berringer@hundredacre.de,1,April,April,2017-04,2017-04,2017-04-01,2017-04-10
2006,18883454,143209,0.0,2016-08-15 14:03:37,Anika Spiehler,Anika,Spiehler,aniclaspi@gmail.com,301834,6,2017-07-15 10:00:00,0.0,NaN,0,NaT,2.0,1,None,2017-07-14 14:37:07,NaN,Rome - Food Tour,36.0,0,12.0,8.0,6,18883454aniclaspi@gmail.com,6,July,July,2017-07,2017-07,2017-07-14,2017-07-15

In [174]:
Greater_than_5.tail()

,bookings_id,clients_id,amount_local_x,booking_time,Full_Name,fname,lname,email,id,events_id,events_datetimes,amount_local_y,amount_converted,cancelled,cancelled_datetime,Total_Pax,is_paid,bookings_note,booking_date,users_id,name_short,pax_max,hard_max,group_size,Counts_Name,Counts_Booking,unique_Person_event,unique_Person_count_event,Event_month,Booking_month,2Month_Period_event,2Month_Period_booking,Booking_DateOnly,Event_DateOnly
226163,40007741,407584,0.0,2017-03-03 14:25:04,Janet Spiehler,Janet,Spiehler,simona.palmisano@gmail.com,408973,1146,2017-03-04 21:00:00,0.0,NaN,0,NaT,2.0,1,,2017-03-03 09:26:29,NaN,VIP Manhattan Nightlife Tour by Limo,14.0,0,14.0,7.0,1,40007741simona.palmisano@gmail.com,1,March,March,2017-03,2017-03,2017-03-03,2017-03-04
226395,18912392,162782,454.0,2017-03-21 22:06:00,Elizabeth Johnson,Elizabeth,Johnson,eghjohnson@bellsouth.net,262202,230,2017-04-06 14:30:00,454.0,506.53,0,NaT,6.0,1,None,2017-03-21 22:06:01,NaN,CUSTOM TOUR - Colosseum with Arena Access & Un...,24.0,0,24.0,6.0,2,18912392eghjohnson@bellsouth.net,2,April,March,2017-04,2017-03,2017-03-21,2017-04-06
226611,18922657,170840,0.0,2017-04-26 08:10:45,Peggy Erlenkotter,Peggy,Erlenkotter,peggy.Erlenkotter@viator.com,272601,214,2017-05-08 08:00:00,189.0,NaN,0,NaT,3.0,1,None,2017-04-26 08:11:25,NaN,API Pristine Sistine 8am (distributors only),30.0,0,15.0,6.0,1,18922657peggy.Erlenkotter@viator.com,1,May,April,2017-05,2017-04,2017-04-26,2017-05-08
226662,18930398,176552,0.0,2017-05-18 07:31:08,Harris Simon,Harris,Simon,harris.simon@gta.com,280305,214,2017-10-05 08:00:00,126.0,NaN,0,NaT,2.0,1,None,2017-05-18 07:32:04,NaN,API Pristine Sistine 8am (distributors only),30.0,0,15.0,7.0,1,18930398harris.simon@gta.com,1,Oct,May,2017-10,2017-05,2017-05-18,2017-10-05
226706,18935032,179871,126.0,2017-05-30 08:01:07,John Williams,John,Williams,john_rs_williams@btinternet.com,284731,214,2017-06-12 08:00:00,126.0,145.38,0,NaT,2.0,1,None,2017-05-30 08:01:07,NaN,API Pristine Sistine 8am (distributors only),30.0,0,15.0,13.0,1,18935032john_rs_williams@btinternet.com,1,June,May,2017-06,2017-05,2017-05-30,2017-06-12

In [112]:
Anika_Spiehler =  pd.DataFrame(Booking_Event_2017_ScleanNeg[Booking_Event_2017_ScleanNeg.Full_Name == "Anika Spiehler"])
Anika_Spiehler

,bookings_id,clients_id,amount_local_x,booking_time,Full_Name,fname,lname,email,id,events_id,events_datetimes,amount_local_y,amount_converted,cancelled,cancelled_datetime,Total_Pax,is_paid,bookings_note,booking_date,users_id,name_short,pax_max,hard_max,group_size,Counts_Name,Counts_Booking,unique_Person_event,unique_Person_count_event,Event_month,Booking_month,2Month_Period_event,2Month_Period_booking,Booking_DateOnly,Event_DateOnly
2006,18883454,143209,0.0,2016-08-15 14:03:37,Anika Spiehler,Anika,Spiehler,aniclaspi@gmail.com,301834,6,2017-07-15 10:00:00,0.0,NaN,0,NaT,2.0,1,None,2017-07-14 14:37:07,NaN,Rome - Food Tour,36.0,0,12.0,8.0,6,18883454aniclaspi@gmail.com,6,July,July,2017-07,2017-07,2017-07-14,2017-07-15
66877,18883454,143209,0.0,2016-08-15 14:03:37,Anika Spiehler,Anika,Spiehler,aniclaspi@gmail.com,327681,79,2017-10-08 13:45:00,0.0,NaN,0,NaT,2.0,1,None,2017-10-06 04:46:45,17.0,Florence - Best of Florence,45.0,0,15.0,8.0,6,18883454aniclaspi@gmail.com,6,Oct,Oct,2017-10,2017-10,2017-10-06,2017-10-08
91342,18883454,143209,0.0,2016-08-15 14:03:37,Anika Spiehler,Anika,Spiehler,aniclaspi@gmail.com,290191,110,2017-06-17 18:45:00,0.0,NaN,0,NaT,2.0,1,None,2017-06-13 22:52:42,NaN,Rome - Pasta Class,14.0,0,14.0,8.0,6,18883454aniclaspi@gmail.com,6,June,June,2017-06,2017-06,2017-06-13,2017-06-17
114629,18883454,143209,0.0,2016-08-15 14:03:37,Anika Spiehler,Anika,Spiehler,aniclaspi@gmail.com,418411,121,2017-10-31 09:45:00,0.0,NaN,0,NaT,2.0,1,None,2017-10-30 18:34:20,NaN,Vatican - Complete Vatican,45.0,0,15.0,8.0,6,18883454aniclaspi@gmail.com,6,Oct,Oct,2017-10,2017-10,2017-10-30,2017-10-31
134237,18883454,143209,0.0,2016-08-15 14:03:37,Anika Spiehler,Anika,Spiehler,aniclaspi@gmail.com,327776,78,2017-10-07 17:00:00,0.0,NaN,0,NaT,2.0,1,None,2017-10-06 14:44:26,17.0,Florence - Dine around Florence: An Authentic ...,28.0,0,14.0,8.0,6,18883454aniclaspi@gmail.com,6,Oct,Oct,2017-10,2017-10,2017-10-06,2017-10-07
199905,18883454,143209,0.0,2016-08-15 14:03:37,Anika Spiehler,Anika,Spiehler,aniclaspi@gmail.com,324100,206,2017-09-24 05:50:00,0.0,NaN,0,NaT,1.0,1,None,2017-09-22 17:08:45,17.0,Rome - Cinque Terre from Rome,15.0,0,15.0,8.0,6,18883454aniclaspi@gmail.com,6,Sept,Sept,2017-09,2017-09,2017-09-22,2017-09-24
223112,40017695,143209,0.0,2017-11-06 15:15:36,Anika Spiehler,Anika,Spiehler,aniclaspi@gmail.com,419626,1145,2017-11-07 10:30:00,0.0,NaN,0,NaT,1.0,1,None,2017-11-06 15:16:28,NaN,"Stories from the Dark Side: Criminals, Gangs &...",40.0,0,20.0,8.0,1,40017695aniclaspi@gmail.com,1,Nov,Nov,2017-11,2017-11,2017-11-06,2017-11-07
225340,40009828,143209,0.0,2017-05-19 13:28:35,Anika Spiehler,Anika,Spiehler,aniclaspi@gmail.com,411188,1149,2017-05-20 09:00:00,0.0,NaN,0,NaT,2.0,1,,2017-05-19 13:28:42,NaN,NEW! Twisted Statue Tour: Under the Skirt of L...,25.0,0,25.0,8.0,1,40009828aniclaspi@gmail.com,1,May,May,2017-05,2017-05,2017-05-19,2017-05-20

In [186]:
Booking_Event_2017_ScleanNeg[Booking_Event_2017_ScleanNeg.Full_Name == "Harris Simon"]

,bookings_id,clients_id,amount_local_x,booking_time,Full_Name,fname,lname,email,id,events_id,events_datetimes,amount_local_y,amount_converted,cancelled,cancelled_datetime,Total_Pax,is_paid,bookings_note,booking_date,users_id,name_short,pax_max,hard_max,group_size,Counts_Name,Counts_Booking,unique_Person_event,unique_Person_count_event,Event_month,Booking_month,2Month_Period_event,2Month_Period_booking,Booking_DateOnly,Event_DateOnly
15642,19149828,383010,262.2,2017-10-06 07:56:04,Harris Simon,Harris,Simon,harriss@qti.qualcomm.com,327704,3,2017-10-06 14:00:00,138.0,166.22,0,NaT,2.0,1,None,2017-10-06 07:56:05,NaN,Rome - Crypts & Catacombs,45.0,1,15.0,7.0,1,19149828harriss@qti.qualcomm.com,1,Oct,Oct,2017-10,2017-10,2017-10-06,2017-10-06
68848,18935943,180561,500.2,2017-06-02 00:29:20,Harris Simon,Harris,Simon,TravelAgent-1496363359@walks.org,285659,79,2017-10-15 13:45:00,118.0,136.44,0,NaT,2.0,1,None,2017-06-02 00:29:21,NaN,Florence - Best of Florence,45.0,0,15.0,7.0,3,18935943TravelAgent-1496363359@walks.org,3,Oct,June,2017-10,2017-06,2017-06-02,2017-10-15
74603,18935943,180561,500.2,2017-06-02 00:29:20,Harris Simon,Harris,Simon,TravelAgent-1496363359@walks.org,285661,36,2017-10-13 08:15:00,138.0,159.57,0,NaT,2.0,1,None,2017-06-02 00:29:22,NaN,Florence - Uffizi Gallery,45.0,1,15.0,7.0,3,18935943TravelAgent-1496363359@walks.org,3,Oct,June,2017-10,2017-06,2017-06-02,2017-10-13
178330,18935948,180565,112.0,2017-06-02 00:43:34,Harris Simon,Harris,Simon,TravelAgent-1496364214@walks.org,285666,9,2017-10-05 15:15:00,112.0,129.51,0,NaT,2.0,1,None,2017-06-02 00:43:35,NaN,Rome - Premium Colosseum,45.0,0,15.0,7.0,1,18935948TravelAgent-1496364214@walks.org,1,Oct,June,2017-10,2017-06,2017-06-02,2017-10-05
187815,18933392,176552,0.0,2017-05-26 07:28:21,Harris Simon,Harris,Simon,harris.simon@gta.com,283103,143,2017-10-14 09:00:00,216.0,NaN,0,NaT,2.0,1,None,2017-05-26 07:28:43,NaN,Florence - Tuscany from Florence,28.0,0,14.0,7.0,1,18933392harris.simon@gta.com,1,Oct,May,2017-10,2017-05,2017-05-26,2017-10-14
205443,18935943,180561,500.2,2017-06-02 00:29:20,Harris Simon,Harris,Simon,TravelAgent-1496363359@walks.org,285660,144,2017-10-17 09:00:00,258.0,298.33,0,NaT,2.0,1,None,2017-06-02 00:29:21,NaN,Venice - Venice in a Day - PACK,48.0,0,12.0,7.0,3,18935943TravelAgent-1496363359@walks.org,3,Oct,June,2017-10,2017-06,2017-06-02,2017-10-17
226662,18930398,176552,0.0,2017-05-18 07:31:08,Harris Simon,Harris,Simon,harris.simon@gta.com,280305,214,2017-10-05 08:00:00,126.0,NaN,0,NaT,2.0,1,None,2017-05-18 07:32:04,NaN,API Pristine Sistine 8am (distributors only),30.0,0,15.0,7.0,1,18930398harris.simon@gta.com,1,Oct,May,2017-10,2017-05,2017-05-18,2017-10-05

In [144]:
Anika_Spiehler.bookings_id.unique().tolist()

[18883454, 40017695, 40009828]

In [145]:
fake = Anika_Spiehler.bookings_id.unique().tolist()

In [208]:
fake[0]

18883454

In [146]:
[s for s in fake]

[18883454, 40017695, 40009828]

In [149]:
Anika_Spiehler[Anika_Spiehler.bookings_id == 18883454].bookings_id.count()

6

In [114]:
Anika_Spiehler_booking_unique = pd.DataFrame(Anika_Spiehler[Anika_Spiehler.bookings_id == 18883454])
Anika_Spiehler_booking_unique

,bookings_id,clients_id,amount_local_x,booking_time,Full_Name,fname,lname,email,id,events_id,events_datetimes,amount_local_y,amount_converted,cancelled,cancelled_datetime,Total_Pax,is_paid,bookings_note,booking_date,users_id,name_short,pax_max,hard_max,group_size,Counts_Name,Counts_Booking,unique_Person_event,unique_Person_count_event,Event_month,Booking_month,2Month_Period_event,2Month_Period_booking,Booking_DateOnly,Event_DateOnly
2006,18883454,143209,0.0,2016-08-15 14:03:37,Anika Spiehler,Anika,Spiehler,aniclaspi@gmail.com,301834,6,2017-07-15 10:00:00,0.0,NaN,0,NaT,2.0,1,None,2017-07-14 14:37:07,NaN,Rome - Food Tour,36.0,0,12.0,8.0,6,18883454aniclaspi@gmail.com,6,July,July,2017-07,2017-07,2017-07-14,2017-07-15
66877,18883454,143209,0.0,2016-08-15 14:03:37,Anika Spiehler,Anika,Spiehler,aniclaspi@gmail.com,327681,79,2017-10-08 13:45:00,0.0,NaN,0,NaT,2.0,1,None,2017-10-06 04:46:45,17.0,Florence - Best of Florence,45.0,0,15.0,8.0,6,18883454aniclaspi@gmail.com,6,Oct,Oct,2017-10,2017-10,2017-10-06,2017-10-08
91342,18883454,143209,0.0,2016-08-15 14:03:37,Anika Spiehler,Anika,Spiehler,aniclaspi@gmail.com,290191,110,2017-06-17 18:45:00,0.0,NaN,0,NaT,2.0,1,None,2017-06-13 22:52:42,NaN,Rome - Pasta Class,14.0,0,14.0,8.0,6,18883454aniclaspi@gmail.com,6,June,June,2017-06,2017-06,2017-06-13,2017-06-17
114629,18883454,143209,0.0,2016-08-15 14:03:37,Anika Spiehler,Anika,Spiehler,aniclaspi@gmail.com,418411,121,2017-10-31 09:45:00,0.0,NaN,0,NaT,2.0,1,None,2017-10-30 18:34:20,NaN,Vatican - Complete Vatican,45.0,0,15.0,8.0,6,18883454aniclaspi@gmail.com,6,Oct,Oct,2017-10,2017-10,2017-10-30,2017-10-31
134237,18883454,143209,0.0,2016-08-15 14:03:37,Anika Spiehler,Anika,Spiehler,aniclaspi@gmail.com,327776,78,2017-10-07 17:00:00,0.0,NaN,0,NaT,2.0,1,None,2017-10-06 14:44:26,17.0,Florence - Dine around Florence: An Authentic ...,28.0,0,14.0,8.0,6,18883454aniclaspi@gmail.com,6,Oct,Oct,2017-10,2017-10,2017-10-06,2017-10-07
199905,18883454,143209,0.0,2016-08-15 14:03:37,Anika Spiehler,Anika,Spiehler,aniclaspi@gmail.com,324100,206,2017-09-24 05:50:00,0.0,NaN,0,NaT,1.0,1,None,2017-09-22 17:08:45,17.0,Rome - Cinque Terre from Rome,15.0,0,15.0,8.0,6,18883454aniclaspi@gmail.com,6,Sept,Sept,2017-09,2017-09,2017-09-22,2017-09-24

# Drop duplicates df.drop_duplicates(subset=['A', 'C'], keep=False)

In [115]:
Anika_Spiehler_booking_unique.drop_duplicates(subset=['events_id'], keep=False)

,bookings_id,clients_id,amount_local_x,booking_time,Full_Name,fname,lname,email,id,events_id,events_datetimes,amount_local_y,amount_converted,cancelled,cancelled_datetime,Total_Pax,is_paid,bookings_note,booking_date,users_id,name_short,pax_max,hard_max,group_size,Counts_Name,Counts_Booking,unique_Person_event,unique_Person_count_event,Event_month,Booking_month,2Month_Period_event,2Month_Period_booking,Booking_DateOnly,Event_DateOnly
2006,18883454,143209,0.0,2016-08-15 14:03:37,Anika Spiehler,Anika,Spiehler,aniclaspi@gmail.com,301834,6,2017-07-15 10:00:00,0.0,NaN,0,NaT,2.0,1,None,2017-07-14 14:37:07,NaN,Rome - Food Tour,36.0,0,12.0,8.0,6,18883454aniclaspi@gmail.com,6,July,July,2017-07,2017-07,2017-07-14,2017-07-15
66877,18883454,143209,0.0,2016-08-15 14:03:37,Anika Spiehler,Anika,Spiehler,aniclaspi@gmail.com,327681,79,2017-10-08 13:45:00,0.0,NaN,0,NaT,2.0,1,None,2017-10-06 04:46:45,17.0,Florence - Best of Florence,45.0,0,15.0,8.0,6,18883454aniclaspi@gmail.com,6,Oct,Oct,2017-10,2017-10,2017-10-06,2017-10-08
91342,18883454,143209,0.0,2016-08-15 14:03:37,Anika Spiehler,Anika,Spiehler,aniclaspi@gmail.com,290191,110,2017-06-17 18:45:00,0.0,NaN,0,NaT,2.0,1,None,2017-06-13 22:52:42,NaN,Rome - Pasta Class,14.0,0,14.0,8.0,6,18883454aniclaspi@gmail.com,6,June,June,2017-06,2017-06,2017-06-13,2017-06-17
114629,18883454,143209,0.0,2016-08-15 14:03:37,Anika Spiehler,Anika,Spiehler,aniclaspi@gmail.com,418411,121,2017-10-31 09:45:00,0.0,NaN,0,NaT,2.0,1,None,2017-10-30 18:34:20,NaN,Vatican - Complete Vatican,45.0,0,15.0,8.0,6,18883454aniclaspi@gmail.com,6,Oct,Oct,2017-10,2017-10,2017-10-30,2017-10-31
134237,18883454,143209,0.0,2016-08-15 14:03:37,Anika Spiehler,Anika,Spiehler,aniclaspi@gmail.com,327776,78,2017-10-07 17:00:00,0.0,NaN,0,NaT,2.0,1,None,2017-10-06 14:44:26,17.0,Florence - Dine around Florence: An Authentic ...,28.0,0,14.0,8.0,6,18883454aniclaspi@gmail.com,6,Oct,Oct,2017-10,2017-10,2017-10-06,2017-10-07
199905,18883454,143209,0.0,2016-08-15 14:03:37,Anika Spiehler,Anika,Spiehler,aniclaspi@gmail.com,324100,206,2017-09-24 05:50:00,0.0,NaN,0,NaT,1.0,1,None,2017-09-22 17:08:45,17.0,Rome - Cinque Terre from Rome,15.0,0,15.0,8.0,6,18883454aniclaspi@gmail.com,6,Sept,Sept,2017-09,2017-09,2017-09-22,2017-09-24

In [ ]:
Anika_Spiehler_booking_unique.events_id

# Building logic and function creation

#### <font color = "Grey">Booking_Event_2017_ScleanNeg</font> => Clean DataFrame Source

In [ ]:
def selection_person():
    data = pd.DataFrame(Booking_Event_2017_ScleanNeg)
    selected_name = [name for name in data.Full_Name.unique()]
    for s in selected_name:
        select_person = pd.DataFrame(data[data.Full_Name == s])
        if select_person.bookings_id.nunique() > 1:
            booking_id = [id  for id in select_person.bookings_id.unique()]
            Selected_booking = pd.DataFrame(select_person[select_person.bookings_id == booking_id])
            Show_Person = pd.DataFrame(Selected_booking.drop_duplicates(subset=['events_id'], keep=False))
            return show_Person
        return select_person

In [180]:
def selection_name(name):
    data = pd.DataFrame(Booking_Event_2017_ScleanNeg)
    select_person = pd.DataFrame(data[data.Full_Name == name])
    booking_id = [id  for id in select_person.bookings_id.unique()]
    if select_person.bookings_id.nunique() > 1:
        for bs in booking_id:
            if select_person[select_person.bookings_id == bs].bookings_id.count() > 1:
                testing = pd.DataFrame(select_person[select_person.bookings_id == bs])
                Show_Person = pd.DataFrame(testing.drop_duplicates(subset=['events_id'], keep=False))
                return Show_Person
    return select_person

In [205]:
def person_maximum():
    Name = []
    Event = []
    Event_DateTime = []
    Booking_DateTime = []
    Amount = []
    data = pd.DataFrame(Booking_Event_2017_ScleanNeg)
    selected_name = [name for name in data.Full_Name.unique()]
    for s in selected_name:
        select_person = pd.DataFrame(data[data.Full_Name == s])
        booking_id = [id  for id in select_person.bookings_id.unique()]
        if select_person.bookings_id.nunique() > 1:
            for bs in booking_id:
                if select_person[select_person.bookings_id == bs].bookings_id.count() > 1:
                    testing = pd.DataFrame(select_person[select_person.bookings_id == bs])
                    Show_Person = pd.DataFrame(testing.drop_duplicates(subset=['events_id'], keep=False))
                    Name.append(Show_Person.Full_Name.unique())
                    Event.append(Show_Person.name_short.unique())
                    Event_DateTime.append(Show_Person.events_datetimes.unique())
                    Booking_DateTime.append(Show_Person.booking_date.unique())
                    Amount.append(Show_Person.amount_local_y.unique())
    return pd.DataFrame(list(zip(Name, Event, Event_DateTime, Booking_DateTime, Amount)))

In [211]:
def person_maxi():
    Name = []
    Event = []
    Event_DateTime = []
    Booking_DateTime = []
    Amount = []
    data = pd.DataFrame(Booking_Event_2017_ScleanNeg)
    selected_name = [name for name in data.Full_Name.unique()]
    for s in selected_name:
        select_person = pd.DataFrame(data[data.Full_Name == s])
        booking_id = [id  for id in select_person.bookings_id.unique()]
        if select_person.bookings_id.nunique() > 1:
            for bs in booking_id:
                if select_person[select_person.bookings_id == bs].bookings_id.count() > 1:
                    testing = pd.DataFrame(select_person[select_person.bookings_id == bs])
                    Show_Person = pd.DataFrame(testing.drop_duplicates(subset=['events_id'], keep=False))
                    Name.append(Show_Person.Full_Name.unique())
                    Event.append(Show_Person.name_short.unique()[0])
                    Event_DateTime.append(Show_Person.events_datetimes.unique()[0])
                    Booking_DateTime.append(Show_Person.booking_date.unique()[0])
                    Amount.append(Show_Person.amount_local_y.unique()[0])
    return pd.DataFrame(list(zip(Name, Event, Event_DateTime, Booking_DateTime, Amount)))

In [206]:
person_maximum()

,0,1,2,3,4
0,[Kevin Wolfe],"[Rome - Food Tour, Rome - Crypts & Catacombs]","[2017-07-11T10:00:00.000000000, 2017-07-12T14:...","[2017-03-13T00:18:27.000000000, 2017-06-30T21:...","[345.0, 0.0]"
1,[Emma del Balzo],"[Rome - Food Tour, Paris - Welcome to Paris, R...","[2017-06-23T10:00:00.000000000, 2017-06-25T17:...","[2017-06-19T13:34:52.000000000, 2017-06-19T13:...","[267.0, 0.0]"
2,[],[],[],[],[]
3,[Ann Johnson],"[Venice - Legendary Venice, Venice - Welcome t...","[2017-10-18T14:00:00.000000000, 2017-10-17T09:...","[2017-10-17T07:41:51.000000000, 2017-10-16T06:...","[130.0, 138.0]"
4,[Jay Berringer],"[Rome - Pasta Class, Rome - Caesars Forum Ligh...","[2017-06-11T18:45:00.000000000, 2017-06-15T20:...",[2017-05-31T15:16:27.000000000],"[79.0, 118.0]"
5,[Marc Estwick],"[Rome - Food Tour, Rome - Borghese Gallery]","[2017-07-07T10:00:00.000000000, 2017-07-09T14:...",[2017-07-06T11:29:59.000000000],"[138.0, 108.0]"
6,[Anika Spiehler],"[Rome - Food Tour, Florence - Best of Florence...","[2017-07-15T10:00:00.000000000, 2017-10-08T13:...","[2017-07-14T14:37:07.000000000, 2017-10-06T04:...",[0.0]
7,[Uma Newton],"[Rome - Food Tour, Rome - Welcome to Rome , Va...","[2017-05-06T10:00:00.000000000, 2017-05-01T17:...","[2016-11-21T16:33:26.000000000, 2016-11-21T16:...","[138.0, 75.0, 173.0, 115.0, 135.0, 353.0, 188...."
8,[Uma Newton],"[Venice - Legendary Venice, Venice - Welcome t...","[2017-04-27T14:00:00.000000000, 2017-04-28T09:...","[2017-02-11T17:54:56.000000000, 2017-02-11T17:...","[128.0, 135.0, 106.0, 136.0, 154.0, 141.0]"
9,[Rosario Villegas],"[Rome - Food Tour, Rome - Pompeii/Amalfi from ...","[2017-10-18T10:00:00.000000000, 2017-10-17T07:...","[2017-10-11T16:12:47.000000000, 2017-07-28T19:...","[175.95, 179.0]"
10,[Melissa Grzanka],"[Rome - Food Tour, Rome - Pompeii/Amalfi from ...","[2017-04-12T10:00:00.000000000, 2017-04-15T07:...",[2016-11-04T02:27:35.000000000],"[138.0, 358.0]"
11,[Connie Pagel],"[Rome - Food Tour, Rome - Welcome to Rome , Ve...","[2017-07-04T10:00:00.000000000, 2017-07-02T17:...","[2016-11-21T16:27:45.000000000, 2016-11-21T16:...","[138.0, 78.0, 258.0, 288.0, 210.0, 148.0]"
12,[Marvelly Fuentes],"[Rome - Food Tour, Rome - Rome in a day ]","[2017-04-03T10:00:00.000000000, 2017-04-01T09:...",[2016-12-04T05:41:52.000000000],"[138.0, 258.0]"
13,[Lori Karis ],"[Rome - Food Tour, Rome - Colosseum & Arena Fl...","[2017-12-30T09:45:00.000000000, 2017-12-31T09:...",[2017-11-01T02:16:46.000000000],"[138.0, 110.0]"
14,[Robyn Wayman],"[Vatican - Complete Vatican, Rome - VIP Coloss...","[2017-04-08T09:45:00.000000000, 2017-04-06T12:...",[2017-01-20T17:28:25.000000000],"[199.0, 280.0]"
15,[Debbie Ferguson],"[Rome - Welcome to Rome , Rome - Pompeii/Amalf...","[2017-04-12T17:00:00.000000000, 2017-04-14T07:...",[2017-01-16T08:55:08.000000000],"[78.0, 358.0]"
16,[Debbie Ferguson],"[Vatican - Complete Vatican, Rome - Premium Co...","[2017-04-15T13:30:00.000000000, 2017-04-13T15:...",[2017-02-10T07:54:58.000000000],"[138.0, 112.0]"
17,[Debbie Ferguson],"[Rome - Borghese Gallery, Rome - Tuscany from ...","[2017-04-19T14:45:00.000000000, 2017-04-24T07:...","[2017-02-22T16:24:01.000000000, 2017-02-22T16:...","[108.0, 278.0]"
18,[Leni Perin],"[Rome - Food Tour, Rome - VIP Caesars Palace]","[2017-03-11T10:00:00.000000000, 2017-03-08T09:...",[2017-01-18T06:01:05.000000000],"[138.0, 112.0]"
19,[Michelle Calamita],"[Florence - Best of Florence, Florence - Uffiz...","[2017-07-09T13:45:00.000000000, 2017-07-09T08:...","[2017-02-05T01:29:51.000000000, 2017-02-05T01:...","[59.0, 69.0]"
20,[Gera Mats],"[Florence - Best of Florence, Venice - Welcome...","[2017-05-24T13:45:00.000000000, 2017-06-01T09:...","[2017-05-24T09:59:38.000000000, 2017-05-17T22:...","[118.0, 138.0]"
21,[Gera Mats],"[Vatican - Complete Vatican, Rome - VIP Coloss...","[2017-05-23T09:45:00.000000000, 2017-05-21T14:...",[2017-02-05T14:57:48.000000000],"[138.0, 190.0]"
22,[Gera Mats],[Florence - Dine around Florence: An Authentic...,"[2017-05-25T17:00:00.000000000, 2017-05-26T09:...",[2017-02-23T02:25:13.000000000],"[150.0, 288.0]"
23,[Scott Johnson],"[Rome - Food Tour, Rome - Welcome to Rome ]","[2017-09-05T10:00:00.000000000, 2017-09-05T17:...",[2017-02-08T17:51:10.000000000],"[138.0, 78.0]"
24,[Saoirse Doyle],"[Rome - Food Tour, Rome - Crypts & Catacombs]","[2017-03-25T10:00:00.000000000, 2017-03-26T14:...","[2017-02-10T12:42:05.000000000, 2017-02-10T12:...",[138.0]
25,[Lora Sieverding],"[Rome - Food Tour, Vatican - St. Peters Basili...","[2017-06-06T10:00:00.000000000, 2017-06-08T08:...","[2017-02-26T20:32:46.000000000, 2017-02-26T20:...","[207.0, 129.0, 281.0]"
26,[David Blinder],"[Rome - Food Tour, Rome - Borghese Gallery]","[2017-03-22T10:00:00.000000000, 2017-03-26T14:...","[2017-03-10T17:59:00.000000000, 2017-03-22T13:...","[276.0, 169.6]"
27,[David Blinder],"[Vatican - Pristine Sistine, Rome - VIP Coloss...","[2017-03-21T07:30:00.000000000, 2017-03-23T12:...","[2017-02-16T19:43:11.000000000, 2017-02-17T16:...","[346.0, 300.8, 492.3]"
28,[Jennifer Lovy],"[Venice - Welcome to Venice, Venice - Food tour]","[2017-03-31T09:00:00.000000000, 2017-04-01T10:...",[2017-02-21T12:08:41.000000000],"[138.0, 148.0]"
29,[Izabela Reszewicz GUIDE TRAINING],"[Rome - Food Tour, Rome - VIP Caesars Palace, ...","[2017-03-06T10:00:00.000000000, 2017-08-12T09:...","[2017-02-24T11:37:00.000000000, 2017-08-11T08:...","[0.0, 28.0]"
30,[],[],[],[],[]
31,[Paula Hughes],"[Rome - Food Tour, Vatican - Pristine Sistine,...","[2017-06-05T10:00:00.000000000, 2017-06-06T07:...","[2017-02-25T11:49:49.000000000, 2017-02-25T11:...","[138.0, 178.0, 112.0]"
32,[Paula Hughes],"[Paris - Louvre, Paris - Catacombs ONLY]","[2017-05-31T18:15:00.000000000, 2017-06-01T12:...",[2017-03-14T13:59:24.000000000],"[138.0, 156.0]"
33,[John Nelson],"[Rome - Food Tour, Rome - Crypts & Catacombs, ...","[2017-03-27T10:00:00.000000000, 2017-03-28T14:...","[2017-02-28T20:50:36.000000000, 2017-02-28T20:...","[343.0, 334.0, 380.0, 875.0, 542.0]"
34,[John Nelson],"[Rome - VIP Colosseum Underground, Florence - ...","[2017-03-26T12:30:00.000000000, 2017-04-03T09:...","[2017-02-28T21:10:32.000000000, 2017-02-28T21:...","[439.0, 700.0]"
35,[Lynn Phillips],"[Rome - Food Tour, Vatican - Complete Vatican,...","[2017-04-21T10:00:00.000000000, 2017-04-20T13:...","[2017-03-01T01:39:49.000000000, 2017-03-01T01:...","[138.0, 112.0]"
36,[Heidi von Maur],"[Rome - Food Tour, Rome - Crypts & Catacombs, ...","[2017-03-18T10:00:00.000000000, 2017-03-21T14:...","[2017-03-04T20:25:38.000000000, 2017-03-04T20:...","[138.0, 135.0, 75.0]"
37,[Sev Borzak - GUIDE TRAINING],"[Rome - Food Tour, Rome - Colosseum at Night, ...","[2017-03-22T10:00:00.000000000, 2017-04-20T19:...","[2017-03-07T11:01:39.000000000, 2017-03-10T08:...",[0.0]
38,[Josephine Ma],"[Rome - Crypts & Catacombs, Rome - Pasta Class...","[2017-11-07T14:00:00.000000000, 2017-11-06T18:...","[2017-10-18T05:35:55.000000000, 2017-10-18T05:...","[0.0, 190.0]"
39,[Josephine Ma],"[Paris - Ile de la CitÃƒÂ©, Paris - Louvre]","[2017-03-21T09:00:00.000000000, 2017-03-22T18:...","[2017-03-19T14:59:06.000000000, 2017-03-19T14:...",[0.0]
40,[Craig Williams],"[Rome - Food Tour, Rome - VIP Caesars Palace]","[2017-04-12T10:00:00.000000000, 2017-04-11T09:...","[2017-03-21T13:49:13.000000000, 2017-03-14T03:...","[138.0, 158.0]"
41,[Laura Russo],"[Rome - VIP Caesars Palace, Vatican - Complete...","[2017-05-13T09:15:00.000000000, 2017-05-11T09:...","[2017-03-18T22:11:36.000000000, 2017-03-18T22:...","[72.0, 69.0, 54.0]"
42,[Paul Lee],"[Vatican - Sistine Express, Rome - Premium Col...","[2017-07-22T08:00:00.000000000, 2017-07-21T08:...",[2017-06-26T22:03:13.000000000],"[117.0, 112.0]"
43,[Gary Allen],"[Rome - Food Tour, Rome - VIP Caesars Palace, ...","[2017-04-22T10:00:00.000000000, 2017-04-24T09:...","[2017-03-22T00:32:17.000000000, 2017-03-22T00:...","[138.0, 144.0, 108.0]"
44,[Patricia Rish],"[Pompeii - Best of Pompeii, Paris - Welcome to...","[2017-04-14T14:30:00.000000000, 2018-03-24T17:...","[2017-04-02T13:25:51.000000000, 2018-01-11T06:...","[174.0, 0.0]"
45,[Jason Wiens],"[Rome - Food Tour, Rome - Welcome to Rome ]","[2017-05-03T10:00:00.000000000, 2017-05-02T17:...","[2017-04-30T16:33:52.000000000, 2017-04-30T16:...","[69.0, 39.0]"
46,[Robyn Meikle],"[Rome - Food Tour, Rome - Welcome to Rome , Va...","[2017-06-14T10:00:00.000000000, 2017-06-11T17:...",[2017-04-19T22:54:25.000000000],"[138.0, 78.0]"
47,[Robyn Meikle],"[Florence - VIP David & Duomo, Florence - Welc...","[2017-06-15T08:00:00.000000000, 2017-06-15T17:...",[2017-04-19T23:40:00.000000000],"[190.0, 68.0]"
48,[CHUCK BULAND],"[Rome - Food Tour, Rome - Premium Colosseum]","[2017-05-19T10:00:00.000000000, 2017-05-19T15:...",[2017-04-20T10:31:05.000000000],"[138.0, 112.0]"
49,[Allison Witherspoon],"[Rome - Food Tour, Rome - Welcome to Rome , Ro...","[2017-07-25T10:00:00.000000000, 2017-07-24T17:...","[2017-04-22T05:05:20.000000000, 2017-07-10T14:...","[138.0, 78.0, 0.0]"
50,[Allison Witherspoon],"[Rome - Driving Tour, Rome - Borghese Gallery]","[2017-07-30T08:45:00.000000000, 2017-07-28T14:...",[2017-04-22T05:40:13.000000000],"[118.0, 108.0]"
51,[Sara Hunt],"[Vatican - Complete Vatican, Rome - Premium Co...","[2017-06-08T09:45:00.000000000, 2017-06-07T08:...","[2017-05-08T13:15:58.000000000, 2017-05-08T13:...","[138.0, 112.0]"
52,[Kasia Chapple],"[Rome - Food Tour, Rome - Rome in a day ]","[2017-06-13T10:00:00.000000000, 2017-06-15T09:...",[2017-04-27T17:13:42.000000000],"[272.0, 605.0]"
53,[Kasia Chapple],"[Rome - Crypts & Catacombs, Rome - Colosseum a...","[2017-06-14T14:00:00.000000000, 2017-06-14T19:...","[2017-05-01T20:49:30.000000000, 2017-05-01T20:...","[335.0, 375.0]"
54,[Kasia Chapple],"[Rome - Crypts & Catacombs, Rome - Colosseum a...","[2017-08-16T14:00:00.000000000, 2017-08-16T19:...",[2017-08-09T17:48:40.000000000],"[135.0, 153.0]"
55,[Elizabeth Oviedo],"[Vatican - Pristine Sistine, Rome - VIP Coloss...","[2017-05-05T07:30:00.000000000, 2017-05-09T09:...","[2017-04-29T01:07:18.000000000, 2017-04-29T01:...","[178.0, 190.0]"
56,[Peter Clarke],"[Rome - Food Tour, Rome - Colosseum at Night]","[2017-07-18T10:00:00.000000000, 2017-07-19T19:...","[2017-07-09T06:05:55.000000000, 2017-04-29T17:...","[207.0, 285.0]"
57,[Amy Hawthorne],"[Rome - Food Tour, Vatican - Complete Vatican,...","[2017-09-27T10:00:00.000000000, 2017-09-26T09:...","[2017-05-04T16:50:14.000000000, 2017-05-04T16:...","[138.0, 190.0, 144.0]"
58,[Suzanne Gamache],"[Rome - Food Tour, Rome - Welcome to Rome , Pa...","[2017-06-24T10:00:00.000000000, 2017-06-23T17:...","[2017-05-11T00:57:18.000000000, 2017-05-11T00:...","[205.0, 112.0, 91.0]"
59,[Niall Duncan],"[Rome - Crypts & Catacombs, Vatican - Pristine...","[2017-07-27T14:00:00.000000000, 2017-07-28T07:...","[2017-05-16T01:31:30.000000000, 2017-05-16T01:...","[138.0, 178.0, 144.0, 130.0]"
60,[Jayne May],"[Rome - Food Tour, Rome - Amalfi Coast from Ro...","[2017-09-25T10:00:00.000000000, 2017-09-22T07:...",[2017-05-16T23:11:53.000000000],"[69.0, 185.0]"
61,[Thomas Vaughn],"[Rome - Food Tour, Rome - Pasta Class]","[2017-06-14T10:00:00.000000000, 2017-06-11T18:...",[2017-05-22T00:11:12.000000000],"[274.0, 305.0]"
62,[Thomas Vaughn],"[Rome - Rome in a day , Rome - Pompeii/Amalfi ...","[2017-06-12T09:15:00.000000000, 2017-06-13T07:...",[2017-05-17T03:10:21.000000000],"[485.0, 701.0]"
63,[Peter Costantini],"[Rome - Food Tour, Rome - Welcome to Rome ]","[2017-09-02T10:00:00.000000000, 2017-08-29T17:...",[2017-05-17T12:38:40.000000000],"[138.0, 78.0]"
64,[PETER WHITE],"[Rome - VIP Caesars Palace, Rome - Borghese Ga...","[2017-06-01T09:15:00.000000000, 2017-06-02T14:...",[2017-05-24T01:46:39.000000000],"[144.0, 108.0]"
65,[Alan Shimshock],"[Rome - Welcome to Rome , Vatican - Pristine S...","[2017-09-15T17:00:00.000000000, 2017-09-16T07:...","[2017-06-01T01:01:01.000000000, 2017-06-01T01:...","[39.0, 89.0, 59.0, 72.0, 95.0, 129.0]"
66,[Clifford Waselowich ],"[Rome - Food Tour, Rome - Welcome to Rome ]","[2017-09-11T10:00:00.000000000, 2017-09-11T17:...",[2017-06-01T01:32:29.000000000],"[207.0, 117.0]"
67,[Clifford Waselowich ],"[Vatican - Pristine Sistine, Rome - Premium Co...","[2017-09-12T07:30:00.000000000, 2017-09-13T08:...",[2017-08-08T05:59:59.000000000],"[178.0, 112.0]"
68,[Paula Matelli],"[Rome - Food Tour, Rome - Crypts & Catacombs, ...","[2017-06-14T10:00:00.000000000, 2017-06-12T14:...",[2017-06-05T00:41:06.000000000],"[138.0, 190.0]"
69,[Carol D Caldwell-Ewart],[Florence - Dine around Florence: An Authentic...,"[2017-06-20T17:00:00.000000000, 2017-06-21T09:...",[2017-06-07T02:49:51.000000000],"[75.0, 144.0, 105.0, 34.0]"
70,[Danielle McKean],"[Rome - Food Tour, Rome - Colosseum at Night]","[2017-07-03T10:00:00.000000000, 2017-07-03T21:...",[2017-06-14T00:31:38.000000000],"[138.0, 158.0]"
71,[Anne Marie Gaglio],"[Rome - Food Tour, Rome - Welcome to Rome , Ro...","[2017-07-29T10:00:00.000000000, 2017-07-29T17:...","[2017-06-23T21:01:30.000000000, 2017-06-23T21:...","[138.0, 78.0, 158.0, 90.0, 370.0]"
72,[Ashley LeFevre],"[Florence - Tuscany from Florence, Florence - ...","[2017-07-12T09:00:00.000000000, 2017-07-13T08:...",[2017-06-27T17:42:50.000000000],"[288.0, 190.0]"
73,[Richard Berman],"[Vatican - Pristine Sistine, Rome - Premium Co...","[2017-07-04T07:30:00.000000000, 2017-07-05T08:...","[2017-03-26T19:16:38.000000000, 2017-03-26T19:...","[178.0, 112.0, 190.0]"
74,[Lone Fuks],"[Rome - Food Tour, Rome - Premium Colosseum]","[2017-07-07T10:00:00.000000000, 2017-07-09T08:...",[2017-07-03T16:51:51.000000000],"[138.0, 110.0]"
75,[Desiree Davison-Kukuk],"[Rome - Food Tour, Rome - Pompeii/Amalfi from ...","[2017-10-11T10:00:00.000000000, 2017-10-10T07:...","[2017-09-29T22:09:47.000000000, 2017-07-04T18:...","[124.2, 358.0, 61.0]"
76,[DANNY GARCIA],"[Rome - Food Tour, Rome - Welcome to Rome ]","[2017-07-28T10:00:00.000000000, 2017-07-18T17:...",[2017-07-08T00:28:54.000000000],"[688.0, 370.0]"
77,[Joyce Smith],"[Rome - VIP Caesars Palace, Vatican - Vatican ...","[2017-07-19T09:15:00.000000000, 2017-07-17T15:...",[2017-07-08T01:22:23.000000000],"[210.0, 169.0]"
78,[Sheryl Williams],"[Rome - Food Tour, Vatican - Pristine Sistine,...","[2017-09-27T10:00:00.000000000, 2017-09-26T07:...","[2017-07-14T14:48:50.000000000, 2017-07-12T20:...","[124.2, 178.0, 190.0, 129.6]"
79,[Natalia Matusz],"[Rome - Food Tour, Rome - VIP Colosseum Underg...","[2017-09-27T10:00:00.000000000, 2017-09-26T14:...",[2017-07-21T17:16:06.000000000],"[138.0, 95.0, 380.0]"
80,[Richard Skevington],"[Rome - Food Tour, Vatican - Pristine Sistine,...","[2017-10-04T10:00:00.000000000, 2017-10-02T07:...","[2017-08-02T01:40:24.000000000, 2017-08-02T01:...","[138.0, 178.0, 112.0]"
81,[Lars Andresen],"[Vatican - Complete Vatican, Rome - Premium Co...","[2017-09-13T13:30:00.000000000, 2017-09-14T15:...",[2017-08-12T12:09:19.000000000],"[138.0, 112.0]"
82,[David McOsker],"[Rome - Food Tour, Rome - Rome in a day ]","[2017-09-06T10:00:00.000000000, 2017-09-07T09:...","[2017-08-13T15:26:29.000000000, 2017-08-13T15:...","[138.0, 258.0]"
83,[David McOsker],[Florence - Dine around Florence: An Authentic...,"[2017-09-14T17:00:00.000000000, 2017-09-14T08:...","[2017-08-13T15:36:55.000000000, 2017-08-13T15:...","[150.0, 190.0]"
84,[Robert Foster],"[Rome - Food Tour, Vatican - Pristine Sistine,...","[2017-10-02T10:00:00.000000000, 2017-09-30T07:...","[2017-08-15T00:29:40.000000000, 2017-08-15T00:...","[138.0, 178.0, 112.0]"
85,[Debbie Pirone],"[Rome - Food Tour, Rome - Welcome to Rome ]","[2017-10-25T10:00:00.000000000, 2017-10-22T17:...",[2017-08-20T17:53:48.000000000],"[138.0, 78.0]"
86,[Debbie Pirone],"[Rome - Crypts & Catacombs, Rome - VIP Caesars...","[2017-10-24T09:00:00.000000000, 2017-10-22T09:...","[2017-08-20T17:47:31.000000000, 2017-08-20T17:...","[138.0, 144.0]"
87,[Debbie Pirone],"[Vatican - Pristine Sistine, Rome - Pompeii/Am...","[2017-10-23T07:30:00.000000000, 2017-10-21T07:...",[2017-08-20T16:45:18.000000000],"[178.0, 358.0]"
88,[Debbie Pirone],"[Rome - Pasta Class, Rome - Borghese Gallery]","[2017-10-20T18:45:00.000000000, 2017-10-20T14:...",[2017-08-20T18:10:15.000000000],"[158.0, 108.0]"
89,[Beth Salter],"[Rome - Food Tour, Rome - Crypts & Catacombs, ...","[2017-10-30T10:00:00.000000000, 2017-10-27T14:...",[2017-10-12T01:28:54.000000000],"[207.0, 267.0]"
90,[Beth Salter],"[Florence - Best of Florence, Florence - Uffiz...","[2017-08-25T13:45:00.000000000, 2017-08-25T08:...","[2017-08-23T02:35:40.000000000, 2017-08-23T02:...","[118.0, 138.0]"
91,[Beth Salter],"[Florence - Best of Florence, Florence - Uffiz...","[2017-11-02T13:45:00.000000000, 2017-11-03T09:...","[2017-10-12T01:53:04.000000000, 2017-10-12T01:...","[177.0, 345.0]"
92,[Lesley Chrisner],"[Rome - Food Tour, Florence - Best of Florence]","[2017-09-15T10:00:00.000000000, 2017-09-23T13:...","[2017-09-08T13:12:17.000000000, 2017-09-08T12:...","[138.0, 118.0]"
93,[Alex Dunn],"[Rome - Food Tour, Rome - Premium Colosseum]","[2017-09-05T10:00:00.000000000, 2017-09-04T15:...","[2017-08-29T18:48:15.000000000, 2017-08-29T18:...","[138.0, 112.0]"
94,[Alex Dunn],"[Florence - Best of Florence, Florence - Uffiz...","[2017-09-07T08:30:00.000000000, 2017-09-08T08:...",[2017-08-29T19:13:00.000000000],"[118.0, 138.0, 150.0]"
95,[Eric Hoehn],"[Rome - Welcome to Rome , Rome - Pasta Class, ...","[2017-09-14T17:00:00.000000000, 2017-09-16T18:...","[2017-08-29T19:40:58.000000000, 2017-08-29T19:...","[78.0, 158.0, 124.2, 100.8, 298.0]"
96,[STEVEN FRIEND],"[Rome - Food Tour, Vatican - Pristine Sistine]","[2017-09-11T10:00:00.000000000, 2017-09-09T07:...",[2017-09-04T16:54:31.000000000],"[138.0, 178.0]"
97,[Johnny Kinkade],"[Rome - Food Tour, Rome - Crypts & Catacombs, ...","[2017-09-29T10:00:00.000000000, 2017-09-29T14:...","[2017-09-07T05:21:42.000000000, 2017-09-07T05:...","[138.0, 258.0, 118.0, 158.0]"
98,[Susan Elizabeth Hartwig],"[Rome - Food Tour, Vatican - Complete Vatican]","[2017-10-07T10:00:00.000000000, 2017-10-09T13:...",[2017-09-08T19:56:51.000000000],[138.0]
99,[Neal Lay-Flurrie],"[Rome - Food Tour, Rome - Colosseum at Night]","[2017-09-26T10:00:00.000000000, 2017-09-25T19:...","[2017-09-09T13:36:23.000000000, 2017-09-09T13:...","[69.0, 79.0]"
100,[Mary Nguyen],"[Rome - Food Tour, Rome - Premium Colosseum]","[2017-09-16T10:00:00.000000000, 2017-09-17T15:...","[2017-09-15T22:51:19.000000000, 2017-09-15T22:...","[138.0, 112.0]"
101,[Amy Grude],"[Rome - Food Tour, Rome - Premium Colosseum]","[2017-09-29T10:00:00.000000000, 2017-09-27T15:...",[2017-09-19T03:04:05.000000000],"[138.0, 112.0]"
102,[Nadia Nufer],"[Rome - Food Tour, Rome - Premium Colosseum]","[2017-09-19T10:00:00.000000000, 2017-09-20T08:...","[2017-09-18T06:45:09.000000000, 2017-09-18T06:...","[138.0, 112.0]"
103,[Amalia DeAngelis],"[Rome - Food Tour, Rome - Alone in Romes Catac...","[2017-10-25T10:00:00.000000000, 2017-10-25T18:...",[2017-09-22T21:00:49.000000000],"[483.0, 495.0]"
104,[Katy Kasper],"[Rome - Tuscany from Rome, Rome - Cinque Terre...","[2017-10-13T07:15:00.000000000, 2017-10-12T05:...","[2017-09-24T19:28:02.000000000, 2017-09-24T19:...","[298.0, 358.0]"
105,[Jeffrey Adams],"[Rome - Food Tour, Rome - Premium Colosseum]","[2017-10-25T10:00:00.000000000, 2017-10-25T15:...",[2017-09-26T15:19:54.000000000],"[138.0, 112.0]"
106,[Kathryn Tuleta],"[Rome - Food Tour, Rome - Premium Colosseum]","[2017-10-10T10:00:00.000000000, 2017-10-10T15:...","[2017-09-27T19:02:36.000000000, 2017-09-27T19:...","[138.0, 112.0]"
107,[Cory Carmin],"[Rome - Food Tour, Rome - Alone in Romes Catac...","[2017-12-09T09:45:00.000000000, 2017-12-10T18:...","[2017-11-25T19:39:00.000000000, 2017-11-25T19:...","[207.0, 216.0]"
108,[Dyer Josephine ],"[Rome - Food Tour, Vatican - Pristine Sistine,...","[2017-12-21T09:45:00.000000000, 2017-12-18T07:...","[2017-12-07T01:13:06.000000000, 2017-12-07T01:...","[69.0, 89.0, 158.0, 79.0]"
109,[Nathan Eccles],"[Rome - Food Tour, Rome - Welcome to Rome , Ro...","[2017-12-28T09:45:00.000000000, 2017-12-27T16:...","[2017-12-17T19:10:12.000000000, 2017-12-17T19:...","[138.0, 78.0, 358.0]"

In [212]:
person_maxi()

IndexError: index 0 is out of bounds for axis 0 with size 0

In [181]:
selection_name("John Williams")

,bookings_id,clients_id,amount_local_x,booking_time,Full_Name,fname,lname,email,id,events_id,events_datetimes,amount_local_y,amount_converted,cancelled,cancelled_datetime,Total_Pax,is_paid,bookings_note,booking_date,users_id,name_short,pax_max,hard_max,group_size,Counts_Name,Counts_Booking,unique_Person_event,unique_Person_count_event,Event_month,Booking_month,2Month_Period_event,2Month_Period_booking,Booking_DateOnly,Event_DateOnly
45501,19134376,371557,693.0,2017-08-16 22:25:44,John Williams,John,Williams,TravelAgent-1502922343@walks.org,312628,7,2017-10-26 07:30:00,178.0,215.75,0,NaT,2.0,1,None,2017-08-16 22:25:46,NaN,Vatican - Pristine Sistine,108.0,0,12.0,13.0,5,19134376TravelAgent-1502922343@walks.org,5,Oct,August,2017-10,2017-08,2017-08-16,2017-10-26
70061,19134376,371557,693.0,2017-08-16 22:25:44,John Williams,John,Williams,TravelAgent-1502922343@walks.org,312625,79,2017-10-18 13:45:00,118.0,143.03,0,NaT,2.0,1,None,2017-08-16 22:25:45,NaN,Florence - Best of Florence,45.0,0,15.0,13.0,5,19134376TravelAgent-1502922343@walks.org,5,Oct,August,2017-10,2017-08,2017-08-16,2017-10-18
134712,19134376,371557,693.0,2017-08-16 22:25:44,John Williams,John,Williams,TravelAgent-1502922343@walks.org,312626,78,2017-10-17 17:00:00,150.0,181.82,0,NaT,2.0,1,None,2017-08-16 22:25:46,NaN,Florence - Dine around Florence: An Authentic ...,28.0,0,14.0,13.0,5,19134376TravelAgent-1502922343@walks.org,5,Oct,August,2017-10,2017-08,2017-08-16,2017-10-17
180417,19134376,371557,693.0,2017-08-16 22:25:44,John Williams,John,Williams,TravelAgent-1502922343@walks.org,312627,9,2017-10-27 15:15:00,112.0,135.76,0,NaT,2.0,1,None,2017-08-16 22:25:46,NaN,Rome - Premium Colosseum,45.0,0,15.0,13.0,5,19134376TravelAgent-1502922343@walks.org,5,Oct,August,2017-10,2017-08,2017-08-16,2017-10-27
185853,19134376,371557,693.0,2017-08-16 22:25:44,John Williams,John,Williams,TravelAgent-1502922343@walks.org,312624,12,2017-10-16 12:45:00,150.0,181.82,0,NaT,2.0,1,None,2017-08-16 22:25:45,NaN,Venice - Secret Passages,23.0,1,15.0,13.0,5,19134376TravelAgent-1502922343@walks.org,5,Oct,August,2017-10,2017-08,2017-08-16,2017-10-16

In [184]:
selection_name("Manuela Valenti GUIDE TRAINING")

,bookings_id,clients_id,amount_local_x,booking_time,Full_Name,fname,lname,email,id,events_id,events_datetimes,amount_local_y,amount_converted,cancelled,cancelled_datetime,Total_Pax,is_paid,bookings_note,booking_date,users_id,name_short,pax_max,hard_max,group_size,Counts_Name,Counts_Booking,unique_Person_event,unique_Person_count_event,Event_month,Booking_month,2Month_Period_event,2Month_Period_booking,Booking_DateOnly,Event_DateOnly
868,124070,95784,0.0,2014-06-19 08:00:00,Manuela Valenti GUIDE TRAINING,Manuela,Valenti GUIDE TRAINING,manuelavalenti4@gmail.com,331273,6,2017-11-23 09:45:00,69.0,NaN,0,NaT,1.0,1,None,2017-10-24 08:00:33,54.0,Rome - Food Tour,36.0,0,12.0,6.0,6,124070manuelavalenti4@gmail.com,6,Nov,Oct,2017-11,2017-10,2017-10-24,2017-11-23
869,124070,95784,0.0,2014-06-19 08:00:00,Manuela Valenti GUIDE TRAINING,Manuela,Valenti GUIDE TRAINING,manuelavalenti4@gmail.com,424594,6,2017-12-16 09:45:00,0.0,NaN,0,NaT,1.0,1,None,2017-12-01 10:26:58,54.0,Rome - Food Tour,36.0,0,12.0,6.0,6,124070manuelavalenti4@gmail.com,6,Dec,Dec,2017-12,2017-12,2017-12-01,2017-12-16
9425,124070,95784,0.0,2014-06-19 08:00:00,Manuela Valenti GUIDE TRAINING,Manuela,Valenti GUIDE TRAINING,manuelavalenti4@gmail.com,331272,3,2017-11-09 14:00:00,69.0,NaN,0,NaT,1.0,1,None,2017-10-24 08:00:01,54.0,Rome - Crypts & Catacombs,45.0,1,15.0,6.0,6,124070manuelavalenti4@gmail.com,6,Nov,Oct,2017-11,2017-10,2017-10-24,2017-11-09
87873,124070,95784,0.0,2014-06-19 08:00:00,Manuela Valenti GUIDE TRAINING,Manuela,Valenti GUIDE TRAINING,manuelavalenti4@gmail.com,331271,16,2017-11-03 08:45:00,0.0,NaN,0,NaT,1.0,1,None,2017-10-24 07:59:29,54.0,Rome - Driving Tour,15.0,0,15.0,6.0,6,124070manuelavalenti4@gmail.com,6,Nov,Oct,2017-11,2017-10,2017-10-24,2017-11-03
140965,124070,95784,0.0,2014-06-19 08:00:00,Manuela Valenti GUIDE TRAINING,Manuela,Valenti GUIDE TRAINING,manuelavalenti4@gmail.com,255794,76,2017-03-01 07:15:00,0.0,NaN,0,NaT,1.0,1,None,2017-02-23 09:59:17,NaN,Rome - Pompeii/Amalfi from Rome,30.0,0,15.0,6.0,6,124070manuelavalenti4@gmail.com,6,March,Feb,2017-03,2017-02,2017-02-23,2017-03-01
199881,124070,95784,0.0,2014-06-19 08:00:00,Manuela Valenti GUIDE TRAINING,Manuela,Valenti GUIDE TRAINING,manuelavalenti4@gmail.com,264590,206,2017-04-18 05:50:00,0.0,NaN,0,NaT,1.0,1,None,2017-03-31 09:23:13,NaN,Rome - Cinque Terre from Rome,15.0,0,15.0,6.0,6,124070manuelavalenti4@gmail.com,6,April,March,2017-04,2017-03,2017-03-31,2017-04-18

In [188]:
selection_name("John Williams")

,bookings_id,clients_id,amount_local_x,booking_time,Full_Name,fname,lname,email,id,events_id,events_datetimes,amount_local_y,amount_converted,cancelled,cancelled_datetime,Total_Pax,is_paid,bookings_note,booking_date,users_id,name_short,pax_max,hard_max,group_size,Counts_Name,Counts_Booking,unique_Person_event,unique_Person_count_event,Event_month,Booking_month,2Month_Period_event,2Month_Period_booking,Booking_DateOnly,Event_DateOnly
45501,19134376,371557,693.0,2017-08-16 22:25:44,John Williams,John,Williams,TravelAgent-1502922343@walks.org,312628,7,2017-10-26 07:30:00,178.0,215.75,0,NaT,2.0,1,None,2017-08-16 22:25:46,NaN,Vatican - Pristine Sistine,108.0,0,12.0,13.0,5,19134376TravelAgent-1502922343@walks.org,5,Oct,August,2017-10,2017-08,2017-08-16,2017-10-26
70061,19134376,371557,693.0,2017-08-16 22:25:44,John Williams,John,Williams,TravelAgent-1502922343@walks.org,312625,79,2017-10-18 13:45:00,118.0,143.03,0,NaT,2.0,1,None,2017-08-16 22:25:45,NaN,Florence - Best of Florence,45.0,0,15.0,13.0,5,19134376TravelAgent-1502922343@walks.org,5,Oct,August,2017-10,2017-08,2017-08-16,2017-10-18
134712,19134376,371557,693.0,2017-08-16 22:25:44,John Williams,John,Williams,TravelAgent-1502922343@walks.org,312626,78,2017-10-17 17:00:00,150.0,181.82,0,NaT,2.0,1,None,2017-08-16 22:25:46,NaN,Florence - Dine around Florence: An Authentic ...,28.0,0,14.0,13.0,5,19134376TravelAgent-1502922343@walks.org,5,Oct,August,2017-10,2017-08,2017-08-16,2017-10-17
180417,19134376,371557,693.0,2017-08-16 22:25:44,John Williams,John,Williams,TravelAgent-1502922343@walks.org,312627,9,2017-10-27 15:15:00,112.0,135.76,0,NaT,2.0,1,None,2017-08-16 22:25:46,NaN,Rome - Premium Colosseum,45.0,0,15.0,13.0,5,19134376TravelAgent-1502922343@walks.org,5,Oct,August,2017-10,2017-08,2017-08-16,2017-10-27
185853,19134376,371557,693.0,2017-08-16 22:25:44,John Williams,John,Williams,TravelAgent-1502922343@walks.org,312624,12,2017-10-16 12:45:00,150.0,181.82,0,NaT,2.0,1,None,2017-08-16 22:25:45,NaN,Venice - Secret Passages,23.0,1,15.0,13.0,5,19134376TravelAgent-1502922343@walks.org,5,Oct,August,2017-10,2017-08,2017-08-16,2017-10-16

# Selecting More than three trip